using Mono.Cecil;
using System.Text;

if (args.Length != 3) throw new ArgumentException("Usage: ContractGen <shim-directory> <contracts-output.cs> <services-output.cs>");
var dir = Path.GetFullPath(args[0]);
var outFile = Path.GetFullPath(args[1]);
Directory.CreateDirectory(Path.GetDirectoryName(outFile)!);

var r = new DefaultAssemblyResolver();
r.AddSearchDirectory(dir);
AssemblyDefinition Load(string n) => AssemblyDefinition.ReadAssembly(Path.Combine(dir, n), new ReaderParameters { AssemblyResolver = r });
var asm = Load("Assembly-CSharp.dll");
var shared = Load("sharedcode.dll");

IEnumerable<TypeDefinition> Flatten(TypeDefinition t) { yield return t; foreach (var n in t.NestedTypes) foreach (var x in Flatten(n)) yield return x; }
var allTypes = asm.MainModule.Types.Concat(shared.MainModule.Types).SelectMany(Flatten).ToList();
var byName = new Dictionary<string, TypeDefinition>();
foreach (var t in allTypes) if (!byName.ContainsKey(t.FullName)) byName[t.FullName] = t;

var services = allTypes.Where(t => t.IsInterface && t.FullName.StartsWith("SharedNet.Api.I") && t.FullName.EndsWith("ServiceApi")).OrderBy(t => t.Name).ToList();

// transitive closure
var seen = new HashSet<string>();
var q = new Queue<TypeReference>();
void Enq(TypeReference tr) { if (tr != null) q.Enqueue(tr); }
foreach (var s in services) foreach (var m in s.Methods) { Enq(m.ReturnType); foreach (var p in m.Parameters) Enq(p.ParameterType); }

Enq(byName["SharedNet.Dto.Realtime.Envelope"]);
var ordered = new List<TypeDefinition>();
while (q.Count > 0)
{
    var tr = q.Dequeue();
    if (tr is null) continue;
    if (tr is GenericInstanceType gi) { foreach (var a in gi.GenericArguments) Enq(a); tr = gi.ElementType; }
    else if (tr is ArrayType at) { Enq(at.ElementType); continue; }
    else if (tr is ByReferenceType br) { Enq(br.ElementType); continue; }
    else if (tr is PointerType pt) { Enq(pt.ElementType); continue; }
    if (byName.TryGetValue(tr.FullName, out var td))
    {
        if (!seen.Add(td.FullName)) continue;
        ordered.Add(td);
        if (td.BaseType != null) Enq(td.BaseType);
        foreach (var f in td.Fields) { if (f.IsStatic) continue; Enq(f.FieldType); }
        foreach (var p in td.Properties) Enq(p.PropertyType);
        foreach (var a in td.CustomAttributes) foreach (var ca in a.ConstructorArguments) Enq(ca.Value as TypeReference);
    }
}

var prim = new Dictionary<string, string> {
    ["System.Void"]="void",["System.Boolean"]="bool",["System.Byte"]="byte",["System.SByte"]="sbyte",
    ["System.Int16"]="short",["System.UInt16"]="ushort",["System.Int32"]="int",["System.UInt32"]="uint",
    ["System.Int64"]="long",["System.UInt64"]="ulong",["System.Single"]="float",["System.Double"]="double",
    ["System.Char"]="char",["System.String"]="string",["System.Object"]="object",["System.Decimal"]="decimal" };

string ElementName(TypeReference tr)
{
    if (tr.IsNested && tr.DeclaringType != null) return ElementName(tr.DeclaringType) + "." + SimpleName(tr);
    var ns = tr.Namespace;
    var name = SimpleName(tr);
    return string.IsNullOrEmpty(ns) ? name : ns + "." + name;
}
string SimpleName(TypeReference tr)
{
    var n = tr.Name;
    var tick = n.IndexOf('`');
    if (tick >= 0) n = n.Substring(0, tick);
    return n;
}
string Render(TypeReference tr)
{
    if (tr is GenericParameter gp) return gp.Name;
    if (tr is ArrayType at) return Render(at.ElementType) + "[" + new string(',', at.Rank - 1) + "]";
    if (tr is ByReferenceType br) return Render(br.ElementType);
    if (tr is GenericInstanceType gi)
    {
        if (gi.ElementType.FullName == "System.Nullable`1")
            return Render(gi.GenericArguments[0]) + "?";
        var baseName = ElementName(gi.ElementType);
        var args = string.Join(", ", gi.GenericArguments.Select(Render));
        return baseName + "<" + args + ">";
    }
    if (prim.TryGetValue(tr.FullName, out var p)) return p;
    // nested
    if (tr.IsNested && tr.DeclaringType != null) return Render(tr.DeclaringType) + "." + SimpleName(tr);
    var ns = tr.Namespace;
    var name = SimpleName(tr);
    if (tr.HasGenericParameters) name += "<" + string.Join(", ", tr.GenericParameters.Select(g => g.Name)) + ">";
    return string.IsNullOrEmpty(ns) ? name : ns + "." + name;
}

bool IsCompilerAttr(string n) => n is "CompilerGeneratedAttribute" or "NullableAttribute" or "NullableContextAttribute"
    or "FieldOffsetAttribute" or "TokenAttribute" or "DefaultMemberAttribute" or "DefaultValueAttribute" or "ObsoleteAttribute";

var sb = new StringBuilder();
sb.AppendLine("// <auto-generated> Generated from the Nordicandia client IL2CPP metadata. </auto-generated>");
sb.AppendLine("#nullable disable");
sb.AppendLine("using System;");
sb.AppendLine("using System.Collections.Generic;");
sb.AppendLine("using MessagePack;");
sb.AppendLine("using MagicOnion;");
sb.AppendLine();
sb.AppendLine("namespace CodeStage.AntiCheat.ObscuredTypes { public struct ObscuredDouble { public double Value; } }");
sb.AppendLine();

string CtorArg(ICustomAttribute a, int i)
{
    if (a.ConstructorArguments.Count <= i) return null;
    var v = a.ConstructorArguments[i].Value;
    if (v is bool b) return b ? "true" : "false";
    return v?.ToString();
}
void EmitTypeAttrs(IndentWriter w, TypeDefinition td)
{
    if (td.FullName == "Game.GameAttributeValue") w.Line("[MessagePackFormatter(typeof(Nordicandia.Contracts.AttributeValueFormatter))]");
    if (td.FullName == "Game.GameAttributeValueDoubleArray") w.Line("[MessagePackFormatter(typeof(Nordicandia.Contracts.AttributeArrayFormatter))]");
    var mp = td.CustomAttributes.FirstOrDefault(a => a.AttributeType.Name == "MessagePackObjectAttribute");
    if (mp != null)
    {
        var k = CtorArg(mp, 0);
        w.Line(k == null ? "[MessagePackObject]" : $"[MessagePackObject({k})]");
    }
    foreach (var u in td.CustomAttributes.Where(a => a.AttributeType.Name == "UnionAttribute"))
    {
        var idx = u.ConstructorArguments[0].Value;
        var ty = u.ConstructorArguments[1].Value as TypeReference;
        w.Line($"[Union({idx}, typeof({Render(ty!)}))]");
    }
    if (td.CustomAttributes.Any(a => a.AttributeType.Name == "DataContractAttribute")) w.Line("[System.Runtime.Serialization.DataContract]");
}
void EmitMemberAttrs(IndentWriter w, ICustomAttributeProvider p)
{
    foreach (var a in p.CustomAttributes)
    {
        if (a.AttributeType.Name == "KeyAttribute")
        {
            var ca = a.ConstructorArguments[0];
            w.Line(ca.Type.FullName == "System.String" ? $"[Key(\"{ca.Value}\")]" : $"[Key({ca.Value})]");
        }
        else if (a.AttributeType.Name == "IgnoreMemberAttribute") w.Line("[IgnoreMember]");
        else if (a.AttributeType.Name == "DataMemberAttribute") w.Line("[System.Runtime.Serialization.DataMember]");
    }
}

void Emit(TypeDefinition td, IndentWriter w)
{
    // generics
    var gen = td.HasGenericParameters ? "<" + string.Join(", ", td.GenericParameters.Select(g => g.Name)) + ">" : "";
    if (td.IsEnum)
    {
        var underlying = td.Fields.FirstOrDefault(f => f.Name == "value__");
        var und = underlying != null ? Render(underlying.FieldType) : "int";
        EmitTypeAttrs(w, td);
        w.Line($"public enum {SimpleName(td)}{gen} : {und}");
        w.BraceOpen();
        foreach (var f in td.Fields.Where(f => f.IsStatic && f.HasConstant))
            w.Line($"{f.Name} = {f.Constant},");
        w.BraceClose();
        return;
    }
    var kind = td.IsInterface ? "interface" : td.IsValueType ? "struct" : "class";
    var mods = "public ";
    if (td.IsAbstract && !td.IsInterface) mods += "abstract ";
    if (td.IsSealed && !td.IsValueType && !td.IsAbstract) mods += "sealed ";
    var baseType = "";
    if (td.BaseType != null && td.BaseType.FullName is not ("System.Object" or "System.ValueType" or "System.Enum"))
        baseType = " : " + Render(td.BaseType);
    if (td.Interfaces.Any(i => i.InterfaceType.FullName == "SharedNet.Dto.Realtime.Message")) baseType += (baseType == "" ? " : " : ", ") + "SharedNet.Dto.Realtime.Message";
    EmitTypeAttrs(w, td);
    w.Line($"{mods}{kind} {SimpleName(td)}{gen}{baseType}");
    w.BraceOpen();
    if (td.FullName == "Game.GameAttributeValueDoubleArray") w.Line("[IgnoreMember] public byte[] WireData { get; set; }");
    // nested types first
    foreach (var nt in td.NestedTypes) Emit(nt, w);
    if (td.IsValueType)
    {
        foreach (var f in td.Fields.Where(f => !f.IsStatic && !f.IsLiteral))
        {
            if (f.Name.StartsWith("<") || f.Name.Contains("k__BackingField")) continue;
            EmitMemberAttrs(w, f);
            if (td.FullName == "Game.GameAttributeValue" && f.Name == "_ValueD" && !f.CustomAttributes.Any(a => a.AttributeType.Name == "IgnoreMemberAttribute")) w.Line("[IgnoreMember]");
            w.Line($"public {Render(f.FieldType)} {f.Name};");
        }
    }
    foreach (var p in td.Properties)
    {
        // `Item` used to be skipped wholesale, which silently dropped
        // AddItemOperationEntry.Item (the only place the client sends full item
        // payloads). Keep the exception narrow so other generated DTOs are unaffected.
        if (p.Name == "Item" && td.FullName != "SharedNet.Api.AddItemOperationEntry") continue;
        var backed = td.Fields.FirstOrDefault(f => f.Name == "<" + p.Name + ">k__BackingField");
        var hasMpAttr = p.CustomAttributes.Any(a => a.AttributeType.Name is "KeyAttribute" or "IgnoreMemberAttribute");
        if (hasMpAttr || backed == null) EmitMemberAttrs(w, p);
        else EmitMemberAttrs(w, backed);
        var hasSet = p.SetMethod != null;
        var acc = hasSet ? "{ get; set; }" : "{ get; }";
        w.Line($"public {Render(p.PropertyType)} {p.Name} {acc}");
    }
    // ensure parameterless ctor exists
    if (!td.IsInterface && !td.IsAbstract && !td.IsValueType && !td.Methods.Any(m => m.IsConstructor && !m.IsStatic && m.Parameters.Count == 0))
        w.Line($"public {SimpleName(td)}() {{ }}");
    w.BraceClose();
}

// services
foreach (var s in services)
{
    var name = s.Name;
    sb.AppendLine($"namespace {s.Namespace}");
    sb.AppendLine("{");
    sb.AppendLine($"    public interface {name} : IService<{name}>");
    sb.AppendLine("    {");
    foreach (var m in s.Methods)
    {
        var ret = Render(m.ReturnType);
        var ps = string.Join(", ", m.Parameters.Select(p => $"{Render(p.ParameterType)} {p.Name}"));
        sb.AppendLine($"        {ret} {m.Name}({ps});");
    }
    sb.AppendLine("    }");
    sb.AppendLine("}");
    sb.AppendLine();
}

// group DTOs by namespace (only top-level, nested emitted recursively)
var topLevel = ordered.Where(t => !t.IsNested).GroupBy(t => t.Namespace ?? "").OrderBy(g => g.Key);
foreach (var g in topLevel)
{
    sb.AppendLine($"namespace {g.Key}");
    sb.AppendLine("{");
    var w = new IndentWriter(sb, 4);
    foreach (var td in g) Emit(td, w);
    sb.AppendLine("}");
    sb.AppendLine();
}

File.WriteAllText(outFile, sb.ToString());

// ---- service implementation stubs (except hand-written ones) ----
var handled = new HashSet<string> { "ILoginServiceApi", "ICatalogServiceApi" };
var s2 = new StringBuilder();
s2.AppendLine("// <auto-generated> MagicOnion service stubs. Replace bodies as needed. </auto-generated>");
s2.AppendLine("#nullable disable");
s2.AppendLine("using MagicOnion;");
s2.AppendLine("using MagicOnion.Server;");
s2.AppendLine("using SharedNet.Api;");
s2.AppendLine("using Nordicandia.Server.State;");
s2.AppendLine();
s2.AppendLine("namespace Nordicandia.Server.Services;");
s2.AppendLine();
int stubCount = 0;
foreach (var s in services)
{
    if (handled.Contains(s.Name)) continue;
    stubCount++;
    var cls = s.Name.Substring(1) + "Impl";
    s2.AppendLine($"public sealed partial class {cls} : ServiceBase<{s.Name}>, {s.Name}");
    s2.AppendLine("{");
    foreach (var m in s.Methods)
    {
        var ret = Render(m.ReturnType);
        var ps = string.Join(", ", m.Parameters.Select(p => $"{Render(p.ParameterType)} {p.Name}"));
        if (s.Name == "ICharacterServiceApi" && m.Name is "CreateCharacter" or "GetCharacterList" or "EnterGameWithCharacter" or "DeleteCharacter" or "AllocateCharacterAttributes" or "UpdateItemFilter") continue;
        if (s.Name == "ICharacterGameEventServiceApi" && m.Name is not "OnGolemGameModeEnded") continue;
        if (s.Name == "ISocialServiceApi" && m.Name is "InspectCharacter") continue;
        if (s.Name == "ICharacterPowerServiceApi") continue;
        if (s.Name == "IGameModeServiceApi") continue;
        if (s.Name == "IOfferingServiceApi" && m.Name is "GetCurrentBlessings" or "MakeOffering") continue;
        if (s.Name == "IUseItemServiceApi" && m.Name is "UseItemWithBuff") continue;
        if (s.Name == "IUserLinkedAccountServiceApi") continue;
        if (s.Name == "IInventoryServiceApi" && m.Name is "ItemOperation") continue;
        if (s.Name == "IVirtualCurrencyServiceApi") continue;
        if (s.Name == "ILeaderboardServiceApi") continue;
        var argType = ret.Substring(ret.IndexOf('<') + 1, ret.LastIndexOf('>') - ret.IndexOf('<') - 1);
        s2.AppendLine($"    public {ret} {m.Name}({ps}) => UnaryResult.FromResult(Defaults.Create<{argType}>());");
    }
    s2.AppendLine("}");
    s2.AppendLine();
}
var servicesOut = Path.GetFullPath(args[2]);
Directory.CreateDirectory(Path.GetDirectoryName(servicesOut)!);
File.WriteAllText(servicesOut, s2.ToString());

Console.WriteLine($"Wrote {outFile}");
Console.WriteLine($"Wrote {servicesOut}");
Console.WriteLine($"Services: {services.Count} ({stubCount} generated stubs, {services.Count - stubCount} hand-written), Types: {ordered.Count}");

public sealed class IndentWriter
{
    private readonly StringBuilder _sb; private readonly int _indent;
    public IndentWriter(StringBuilder sb, int indent) { _sb = sb; _indent = indent; }
    public void Line(string s) => _sb.Append(new string(' ', _indent)).AppendLine(s);
    public void BraceOpen() => _sb.Append(new string(' ', _indent)).AppendLine("{");
    public void BraceClose() => _sb.Append(new string(' ', _indent)).AppendLine("}");
}
