// <auto-generated> from tools/web-content/fixtures/character_attributes.json origin 0.
// Global Base_* attribute defaults shared by all characters (client constants).
namespace Nordicandia.Server.State;

internal static class CharacterBaseline
{
    /// <summary>Base_* attribute id -> default value.</summary>
    internal static readonly IReadOnlyDictionary<int, double> BaseAttributes = new Dictionary<int, double>
    {
        [40] = 1.5, // Base_Stamina_Multiplier
        [101] = 15, // Base_Strength
        [102] = 15, // Base_Dexterity
        [103] = 15, // Base_Intelligence
        [104] = 15, // Base_Vitality
        [123] = 10, // Base_Constitution
        [124] = 10, // Base_Agility
        [203] = 15, // Base_AttackRating
        [250] = 1.25, // Base_Armor_Multiplier
        [255] = 1.25, // Base_Evasion_Multiplier
        [300] = 250, // Base_Life_Max
        [304] = 0.01, // Base_Life_Regen_Percent
        [325] = 100, // Base_Mana_Max
        [329] = 0.02, // Base_Mana_Regen_Percent
        [339] = 0.03, // Base_Life_Leech_Rate
        [342] = 1, // Base_Life_Leech_Maximum_Recovery_Per_Instance
        [345] = 0.3, // Base_Life_Leech_Maximum_Recovery
        [360] = 1.25, // Base_Experience_Percent
        [397] = 0.5, // Base_Melee_Auto_Attacks_Splash_Damage_Percent
        [398] = 160, // Base_Melee_Auto_Attacks_Splash_Damage_Cone_Angle
        [399] = 2, // Base_Melee_Auto_Attacks_Splash_Damage_Cone_Radius_Multiplier
        [400] = 1, // Base_Cast_Speed_Percent
        [501] = 1.25, // Base_Weapon_Physical_Damage_Percent
        [580] = 1, // Base_Glancing_Hit_Debuff_Duration
        [592] = 1.5, // Base_Life_Multiplier
        [600] = 1.25, // Base_AttackSpell_Power_Percent
        [601] = 1.25, // Base_HealSpell_Power_Percent
        [669] = 0.5, // Base_Blocked_Damage_Taken_Multiplier
        [700] = 1, // Base_Crit_Chance_Multiplier
        [712] = 1, // Base_Crit_Damage
        [800] = 0.05, // Base_Dodge_Chance
        [804] = 0.05, // Base_Dodge_Chance_Spell
        [1401] = 1.25, // Base_Weapon_Fire_Damage_Percent
        [1501] = 1.25, // Base_Weapon_Cold_Damage_Percent
        [1601] = 1.25, // Base_Weapon_Lightning_Damage_Percent
        [1701] = 1.25, // Base_Weapon_Poison_Damage_Percent
        [3100] = 1.25, // Base_ForceField_Multiplier
        [3105] = 0.2, // Base_ForceField_Regen_Percent
        [3109] = 3, // Base_ForceField_Regen_Delay
    };
}
