// <auto-generated> by tools/web-content/export_powers.py — do not edit by hand.
using Nordicandia.Simulation;

namespace Nordicandia.Server.WebApi;

public static partial class PowerCatalog
{
    public static readonly IReadOnlyDictionary<int, ClassPowers> ByClass = new Dictionary<int, ClassPowers>
    {
        [0] = new ClassPowers("Warrior", new SkillProfile[]
        {
            new(0, "Slam", "Slam the ground in front of you to deal {0} weapon damage to enemies in a line.", "Slam", "strike", 5.5D, 15.0D, 0.0D, 35.0D, 0.0D, 0.0D, 0.0D, "client-verified", new Dictionary<string, double> { ["Base_Power_Weapon_Damage_Multiplier"] = 5.5D, ["Base_Cooldown"] = 15.0D, ["Base_Mana_Cost"] = 35.0D, ["Slam_Max_Distance"] = 15.0D }),
            new(1, "Might", "Increases your strength by {0}% for {1} seconds.", "Might", "rally", 0.0D, 30.0D, 0.0D, 0D, 0.15D, 0.75D, 10.0D, "client-verified", new Dictionary<string, double> { ["Strength_Bonus_Percent"] = 0.75D, ["Buff_Duration"] = 10.0D, ["Base_Cooldown"] = 30.0D }),
            new(2, "Pounce", "", "Pounce", "strike", 0.25D, 10.0D, 0.0D, 15.0D, 0.0D, 0.0D, 0.0D, "client-verified", new Dictionary<string, double> { ["Base_Power_Weapon_Damage_Multiplier"] = 0.25D, ["Base_Cooldown"] = 10.0D, ["Base_Mana_Cost"] = 15.0D }),
        }, new PassiveProfile("Overkill", "Your melee overkill damage has {0}% chance to generate a new attack for the remaining damage on another nearby enemy.", "Overkill", "might", 1.0D, 0.0D, "client-verified")),
        [4] = new ClassPowers("Hunter", new SkillProfile[]
        {
            new(0, "RapidFire", "Increases your attack speed by {0}% for {1} second(s).\n{2} second(s) cooldown.", "RapidFire", "rally", 0.0D, 25.0D, 0.0D, 30.0D, 0.15D, 0.25D, 6.0D, "client-verified", new Dictionary<string, double> { ["Base_Cooldown"] = 25.0D, ["Base_Mana_Cost"] = 30.0D }),
            new(1, "ArrowRain", "Fire a rain of arrows towards a selected area of {0} units for {1} seconds. Deals {2}% weapon damage per second.\n{3} second(s) cooldown.\nCosts {4} mana.", "ArrowRain", "nova", 1.4D, 25.0D, 3.0D, 20.0D, 0.0D, 0.0D, 0.0D, "client-verified", new Dictionary<string, double> { ["Base_Mana_Cost"] = 20.0D, ["Base_Cooldown"] = 25.0D, ["Base_Power_Radius"] = 3.0D }),
            new(2, "SummonWolf", "Summon a wolf companion with {0}% of your health and {1}% of your damage, which defends you and helps you find {2}% more monsters.", "SummonWolf", "rally", 0.0D, 45.0D, 0.0D, 45.0D, 0.2D, 0.15D, 8.0D, "client-verified", new Dictionary<string, double> { ["Base_Cooldown"] = 45.0D, ["Base_Mana_Cost"] = 45.0D }),
        }, new PassiveProfile("Precision", "", "Precision", "might", 0.5D, 0.05D, "client-verified")),
        [5] = new ClassPowers("Mage", new SkillProfile[]
        {
            new(0, "ChainLightning", "Cast a jolt of lightning that deals {0}% weapon damage as Lightning and then jumps to additional nearby enemies. Each jump reduces the damage by {1}%. The lightning will dissipate after {2} jumps.\n{3} second(s) cooldown.\nCosts {4} mana.", "ChainLightning", "chain", 2.5D, 20.0D, 5.5D, 0D, 0.0D, 0.0D, 0.0D, "client-verified", new Dictionary<string, double> { ["Base_Power_Weapon_Damage_Multiplier"] = 2.5D, ["ChainLightning_Max_Num_Chains"] = 4.0D, ["Base_Cooldown"] = 20.0D }),
            new(1, "Teleport", "", "Teleport", "rally", 2.2D, 12.0D, 0.0D, 20.0D, 0.0D, 0.0D, 0.0D, "client-verified", new Dictionary<string, double> { ["Base_Cooldown"] = 12.0D, ["Base_Mana_Cost"] = 20.0D }),
            new(2, "IceNova", "Cast an Ice Nova that deals {0}% weapon damage as Cold and hits all enemies within {1} units, freezing them for {2} seconds.\n{3} second(s) cooldown.\nCosts {4} mana.", "IceNova", "nova", 0.5D, 30.0D, 6.0D, 0D, 0.0D, 0.0D, 2.0D, "client-verified", new Dictionary<string, double> { ["Base_Power_Radius"] = 6.0D, ["Base_Power_Weapon_Damage_Multiplier"] = 0.5D, ["Power_Freeze_Duration"] = 2.0D, ["Base_Cooldown"] = 30.0D }),
        }, new PassiveProfile("Hubris", "Increases your total Intelligence by {0}%", "Hubris", "might", 0.3D, 0.0D, "client-verified")),
        [6] = new ClassPowers("Necromancer", new SkillProfile[]
        {
            new(0, "SummonSkeleton", "", "SummonSkeleton", "summon", 0.0D, 10.0D, 0.0D, 0D, 0.2D, 0.15D, 8.0D, "client-verified", new Dictionary<string, double> { ["Minion_Inheritance_Weapon_Damage_Bonus_Percent"] = 0.15D, ["Minion_Inheritance_Attack_Speed_Bonus_Percent"] = 0.8D, ["Minion_Inheritance_Movement_Speed_Bonus_Percent"] = 1.1D, ["Minion_Inheritance_Life_Bonus_Percent"] = 0.5D, ["Minion_Inheritance_Force_Field_Bonus_Percent"] = 0.3D, ["Minion_Inheritance_Armor_Evasion_Bonus_Percent"] = 0.75D, ["Minion_Inheritance_Resistances_Bonus_Percent"] = 0.75D, ["Minion_Inheritance_Crit_Chance_Bonus_Percent"] = 1.0D, ["Minion_Inheritance_Crit_Damage_Bonus_Percent"] = 1.0D, ["Base_Cooldown"] = 10.0D }),
            new(1, "AstralWalk", "", "AstralWalk", "mobility", 2.2D, 16.0D, 0.0D, 0D, 0.0D, 0.0D, 0.0D, "client-verified", new Dictionary<string, double> { ["AstralWalk_Movement_Speed_Bonus_Percent"] = 10.0D, ["Base_Cooldown"] = 16.0D }),
            new(2, "Shadowbolt", "", "ShadowBolt", "nova", 3.0D, 15.0D, 2.5D, 30.0D, 0.0D, 0.0D, 0.0D, "client-verified", new Dictionary<string, double> { ["Base_Power_Weapon_Damage_Multiplier"] = 3.0D, ["Power_Weapon_Damage_Multiplier_2"] = 0.5D, ["Base_Power_Radius"] = 2.5D, ["Base_Cooldown"] = 15.0D, ["Base_Mana_Cost"] = 30.0D }),
        }, new PassiveProfile("Bodyguard", "", "Bodyguard", "might", 0.1D, 0.05D, "client-verified")),
    };

    public static readonly IReadOnlyDictionary<string, IReadOnlyList<MasteryProfile>> MasteriesByPower = new Dictionary<string, IReadOnlyList<MasteryProfile>>
    {
        ["Might"] = new MasteryProfile[]
        {
            new("MasteryMightImprovedMight", 82, 1, new MasterySpec[] { new MasterySpec(109, "Strength_Bonus_Percent", 0.03D, 0.0D, 0) }),
            new("MasteryMightFuriousRage", 84, 5, new MasterySpec[] { new MasterySpec(6, "Amplify_Damage_Taken_Percent", 0.02D, 0.0D, 0), new MasterySpec(244, "attr_244", 0.04D, 0.0D, 0) }),
            new("MasteryMightPiercingStrength", 86, 5, new MasterySpec[] { new MasterySpec(717, "Armor_Piercing_Percent", 0.02D, 0.0D, 0), new MasterySpec(79, "Base_Cooldown", 0.0D, 0.0D, 2), new MasterySpec(232, "Power_Duration", 360.0D, 0.0D, 0) }),
            new("MasteryMightDuration", 221, 6, new MasterySpec[] {  }),
            new("MasteryMightObsession", 399, 5, new MasterySpec[] {  }),
            new("MasteryMightDisarm", 401, 5, new MasterySpec[] {  }),
            new("MasteryMightSturdiness", 403, 5, new MasterySpec[] {  }),
        },
        ["IncrementalFortress"] = new MasteryProfile[]
        {
            new("MasteryIncrementalFortressImprovedIncrementalFortress", 88, 25, new MasterySpec[] { new MasterySpec(1003, "Resistance_Stun", 0.02D, 0.0D, 0) }),
            new("MasteryIncrementalFortressElementalFortress", 120, 5, new MasterySpec[] { new MasterySpec(1002, "Resistance_All", 0.0005D, 0.0D, 0), new MasterySpec(79, "Base_Cooldown", 20.0D, 0.0D, 0), new MasterySpec(232, "Power_Duration", 120.0D, 0.0D, 0), new MasterySpec(252, "Armor_Bonus_Percent", 0.0D, 0.0075D, 1) }),
            new("MasteryIncrementalFortressHeavyFortress", 122, 5, new MasterySpec[] { new MasterySpec(252, "Armor_Bonus_Percent", 0.005D, 0.0D, 0), new MasterySpec(330, "Mana_Regen_Bonus", 0.01D, 0.0D, 1), new MasterySpec(79, "Base_Cooldown", 4.0D, 0.0D, 1) }),
            new("MasteryIncrementalFortressDuration", 223, 6, new MasterySpec[] {  }),
            new("MasteryIncrementalFortressCounterAttack", 405, 5, new MasterySpec[] {  }),
            new("MasteryIncrementalFortressBlock", 407, 5, new MasterySpec[] {  }),
        },
        ["WarStomp"] = new MasteryProfile[]
        {
            new("MasteryWarStompImprovedWarStomp", 90, 1, new MasterySpec[] { new MasterySpec(58, "Base_Power_Weapon_Damage_Multiplier", 0.04D, 0.0D, 0) }),
            new("MasteryWarStompKnockOut", 124, 5, new MasterySpec[] { new MasterySpec(232, "Power_Duration", 0.2D, 0.0D, 0), new MasterySpec(79, "Base_Cooldown", 5.0D, 0.0D, 1) }),
            new("MasteryWarStompGroundShaker", 126, 6, new MasterySpec[] { new MasterySpec(79, "Base_Cooldown", 40.0D, 0.0D, 0), new MasterySpec(850, "Potion_More_Mana_During_Health_Potion", 0.0D, 12.0D, 0), new MasterySpec(166, "Buff_Duration", 60.0D, 0.0D, 0) }),
            new("MasteryWarStompForceOfTheMinotaur", 227, 10, new MasterySpec[] {  }),
            new("MasteryWarStompBlazingStomp", 409, 5, new MasterySpec[] {  }),
            new("MasteryWarStompGraspingVines", 411, 5, new MasterySpec[] { new MasterySpec(850, "Potion_More_Mana_During_Health_Potion", 0.0D, 12.0D, 0) }),
        },
        ["Sprint"] = new MasteryProfile[]
        {
            new("MasterySprintCharge", 92, 5, new MasterySpec[] { new MasterySpec(261, "Power_Sprint_Charge_Radius", 2.5D, 0.0D, 0), new MasterySpec(850, "Potion_More_Mana_During_Health_Potion", -1.0D, 8.0D, 0) }),
            new("MasterySprintImprovedSprint", 96, 15, new MasterySpec[] { new MasterySpec(1101, "Movement_Speed_Bonus_Percent", 0.02D, 0.0D, 0) }),
            new("MasterySprintMarathon", 118, 6, new MasterySpec[] { new MasterySpec(79, "Base_Cooldown", 60.0D, 0.0D, 0), new MasterySpec(232, "Power_Duration", 120.0D, 0.0D, 0), new MasterySpec(1101, "Movement_Speed_Bonus_Percent", -0.08D, 0.0D, 0) }),
            new("MasterySprintAttackSpeed", 413, 5, new MasterySpec[] {  }),
            new("MasterySprintChargeFirstHit", 415, 5, new MasterySpec[] { new MasterySpec(850, "Potion_More_Mana_During_Health_Potion", -1.0D, 8.0D, 0) }),
            new("MasterySprintAcrobatics", 417, 5, new MasterySpec[] {  }),
        },
        ["Retaliation"] = new MasteryProfile[]
        {
            new("MasteryRetaliationImprovedRetaliation", 94, 10, new MasterySpec[] { new MasterySpec(58, "Base_Power_Weapon_Damage_Multiplier", 0.02D, 0.0D, 0) }),
            new("MasteryRetaliationReflexes", 128, 5, new MasterySpec[] { new MasterySpec(79, "Base_Cooldown", 4.0D, 0.0D, 1), new MasterySpec(183, "attr_183", 1.0D, 0.0D, 0) }),
            new("MasteryRetaliationEndurance", 130, 6, new MasterySpec[] { new MasterySpec(79, "Base_Cooldown", 60.0D, 0.0D, 0), new MasterySpec(232, "Power_Duration", 20.0D, 0.0D, 0), new MasterySpec(183, "attr_183", -1.0D, -5.0D, 0) }),
            new("MasteryRetaliationRange", 235, 5, new MasterySpec[] {  }),
            new("MasteryRetaliationThorns", 419, 5, new MasterySpec[] {  }),
            new("MasteryRetaliationThrownAxe", 421, 5, new MasterySpec[] {  }),
        },
        ["Shatter"] = new MasteryProfile[]
        {
            new("MasteryShatterImprovedShatter", 2, 1, new MasterySpec[] { new MasterySpec(58, "Base_Power_Weapon_Damage_Multiplier", 0.05D, 0.0D, 0) }),
            new("MasteryShatterSplittingPower", 6, 5, new MasterySpec[] { new MasterySpec(717, "Armor_Piercing_Percent", 0.06D, 0.0D, 0) }),
            new("MasteryShatterOverpower", 8, 5, new MasterySpec[] { new MasterySpec(58, "Base_Power_Weapon_Damage_Multiplier", 0.25D, 3.0D, 0), new MasterySpec(82, "Shatter_Overpower_Less_Weapon_Damage_Percent", 0.0D, -0.5D, 0), new MasterySpec(81, "Shatter_Overpower_Less_Weapon_Damage_Duration", -1.0D, 8.0D, 0) }),
            new("MasteryShatterPrecisionStrike", 132, 5, new MasterySpec[] { new MasterySpec(204, "AttackRating_Bonus_Percent", 0.3D, 0.0D, 0) }),
            new("MasteryShatterAutoShatter", 225, 6, new MasterySpec[] {  }),
            new("MasteryShatterCrushingBlow", 391, 5, new MasterySpec[] {  }),
            new("MasteryShatterLightningStrike", 393, 5, new MasterySpec[] {  }),
        },
        ["Hunger"] = new MasteryProfile[]
        {
            new("MasteryHungerInsatiableHunger", 98, 10, new MasterySpec[] { new MasterySpec(313, "Physical_Life_Leech", 0.005D, 0.0D, 0), new MasterySpec(314, "Fire_Life_Leech", 0.005D, 0.0D, 0), new MasterySpec(315, "Cold_Life_Leech", 0.005D, 0.0D, 0), new MasterySpec(316, "Lightning_Life_Leech", 0.005D, 0.0D, 0), new MasterySpec(317, "Poison_Life_Leech", 0.005D, 0.0D, 0) }),
            new("MasteryHungerHeartseeker", 100, 5, new MasterySpec[] { new MasterySpec(247, "attr_247", 0.02D, 0.0D, 0) }),
            new("MasteryHungerAwakenedHunger", 104, 6, new MasterySpec[] { new MasterySpec(79, "Base_Cooldown", 120.0D, 0.0D, 0), new MasterySpec(850, "Potion_More_Mana_During_Health_Potion", 20.0D, 120.0D, 1), new MasterySpec(166, "Buff_Duration", 240.0D, 0.0D, 0), new MasterySpec(346, "Life_Leech_Maximum_Recovery_Bonus_Percent", 0.04D, 0.0D, 1) }),
            new("MasteryHungerRestoreLifeOnAwaken", 423, 5, new MasterySpec[] { new MasterySpec(850, "Potion_More_Mana_During_Health_Potion", 20.0D, 120.0D, 1) }),
            new("MasteryHungerCellRecovery", 425, 10, new MasterySpec[] {  }),
            new("MasteryHungerFinishingBlow", 427, 5, new MasterySpec[] {  }),
        },
        ["PowerShot"] = new MasteryProfile[]
        {
            new("MasteryPowerShotPiercingArrow", 143, 5, new MasterySpec[] { new MasterySpec(303, "Base_Action_Speed", 0.2D, 0.0D, 1), new MasterySpec(230, "Power_Projectile_Pierce_Chance", 0.02D, 0.0D, 0) }),
            new("MasteryPowerShotImprovedPowerShot", 145, 1, new MasterySpec[] { new MasterySpec(58, "Base_Power_Weapon_Damage_Multiplier", 0.1D, 0.0D, 0) }),
            new("MasteryPowerShotPowerAttacks", 147, 6, new MasterySpec[] { new MasterySpec(319, "Power_Backflip_SafetyFlip_Health_Threshold_Percent", 120.0D, 0.0D, 0), new MasterySpec(318, "Power_Auto_Cast_On_Auto_Attack_Chance", -1.0D, 20.0D, 0), new MasterySpec(79, "Base_Cooldown", 30.0D, 0.0D, 0) }),
            new("MasteryPowerShotQuickshot", 237, 10, new MasterySpec[] {  }),
            new("MasteryPowerShotHomingShot", 449, 5, new MasterySpec[] {  }),
            new("MasteryPowerShotLessManaCost", 451, 5, new MasterySpec[] {  }),
        },
        ["Backflip"] = new MasteryProfile[]
        {
            new("MasteryBackflipSafetyFlip", 149, 6, new MasterySpec[] { new MasterySpec(322, "attr_322", 1.0D, 0.0D, 0), new MasterySpec(166, "Buff_Duration", 300.0D, 0.0D, 0), new MasterySpec(79, "Base_Cooldown", 45.0D, 0.0D, 0) }),
            new("MasteryBackflipHaste", 151, 10, new MasterySpec[] { new MasterySpec(1101, "Movement_Speed_Bonus_Percent", 1.0D, 0.0D, 0) }),
            new("MasteryBackflipFrontflip", 153, 1, new MasterySpec[] { new MasterySpec(369, "attr_369", 1.0D, 0.0D, 0) }),
            new("MasteryBackflipAcrobatics", 157, 5, new MasterySpec[] { new MasterySpec(79, "Base_Cooldown", 3.0D, 0.0D, 1) }),
            new("MasteryBackflipMirror", 239, 5, new MasterySpec[] { new MasterySpec(1101, "Movement_Speed_Bonus_Percent", 1.0D, 0.0D, 0) }),
            new("MasteryBackflipDodge", 453, 5, new MasterySpec[] {  }),
            new("MasteryBackflipPowerShot", 455, 5, new MasterySpec[] {  }),
        },
        ["ArrowRain"] = new MasteryProfile[]
        {
            new("MasteryArrowRainImprovedArrowRain", 16, 1, new MasterySpec[] { new MasterySpec(58, "Base_Power_Weapon_Damage_Multiplier", 0.1D, 0.0D, 0) }),
            new("MasteryArrowRainArrowCascade", 18, 6, new MasterySpec[] { new MasterySpec(193, "Base_Power_Radius", 0.5D, 0.0D, 0), new MasterySpec(79, "Base_Cooldown", 4.0D, 0.0D, 0) }),
            new("MasteryArrowRainPrecisionArrows", 20, 5, new MasterySpec[] { new MasterySpec(79, "Base_Cooldown", 5.0D, 0.0D, 1), new MasterySpec(193, "Base_Power_Radius", 0.25D, 0.0D, 1) }),
            new("MasteryArrowRainTorrent", 243, 5, new MasterySpec[] { new MasterySpec(58, "Base_Power_Weapon_Damage_Multiplier", 0.1D, 0.0D, 0) }),
            new("MasteryArrowRainPenetrate", 457, 5, new MasterySpec[] {  }),
            new("MasteryArrowRainPureArrows", 459, 5, new MasterySpec[] {  }),
        },
        ["Fade"] = new MasteryProfile[]
        {
            new("MasteryFadeBlur", 155, 1, new MasterySpec[] { new MasterySpec(257, "Evasion_Bonus_Percent", 0.1D, 0.0D, 0) }),
            new("MasteryFadeDarkness", 159, 6, new MasterySpec[] { new MasterySpec(79, "Base_Cooldown", 60.0D, 0.0D, 0), new MasterySpec(166, "Buff_Duration", 180.0D, 0.0D, 0), new MasterySpec(1101, "Movement_Speed_Bonus_Percent", 0.02D, 0.0D, 0), new MasterySpec(257, "Evasion_Bonus_Percent", 0.05D, -1.0D, 0) }),
            new("MasteryFadeQuickReflexes", 161, 5, new MasterySpec[] { new MasterySpec(79, "Base_Cooldown", 4.0D, 0.0D, 1), new MasterySpec(801, "Dodge_Chance_Bonus_Percent", 0.1D, 0.0D, 0), new MasterySpec(805, "Dodge_Chance_Spell_Percent_Bonus", 0.1D, 0.0D, 0) }),
            new("MasteryFadeSpeed", 241, 5, new MasterySpec[] {  }),
            new("MasteryFadeRegenerate", 461, 5, new MasterySpec[] {  }),
            new("MasteryFadeShadowAssassin", 463, 5, new MasterySpec[] {  }),
        },
        ["RapidFire"] = new MasteryProfile[]
        {
            new("MasteryRapidFireEnduringSwiftness", 163, 6, new MasterySpec[] { new MasterySpec(79, "Base_Cooldown", 120.0D, 0.0D, 0), new MasterySpec(166, "Buff_Duration", 300.0D, 0.0D, 0), new MasterySpec(451, "Attack_Speed_Bonus_Percent", 0.05D, -2.0D, 0) }),
            new("MasteryRapidFireBattery", 165, 5, new MasterySpec[] { new MasterySpec(79, "Base_Cooldown", 2.0D, 0.0D, 1), new MasterySpec(373, "attr_373", 0.0D, 1.0D, 0), new MasterySpec(451, "Attack_Speed_Bonus_Percent", 0.15D, 0.0D, 0) }),
            new("MasteryRapidFireImprovedRapidFire", 167, 1, new MasterySpec[] { new MasterySpec(371, "Power_Projectile_Speed_Bonus", 0.05D, 0.0D, 0) }),
            new("MasteryRapidFireAttackRange", 465, 5, new MasterySpec[] {  }),
            new("MasteryRapidFireMaxAttackSpeed", 467, 5, new MasterySpec[] {  }),
            new("MasteryRapidFireReducedStandStill", 469, 5, new MasterySpec[] {  }),
        },
        ["Multishot"] = new MasteryProfile[]
        {
            new("MasteryMultishotImprovedMultishot", 171, 1, new MasterySpec[] { new MasterySpec(58, "Base_Power_Weapon_Damage_Multiplier", 0.05D, 0.0D, 0) }),
            new("MasteryMultishotBroadside", 173, 5, new MasterySpec[] { new MasterySpec(79, "Base_Cooldown", 1.0D, 0.0D, 1), new MasterySpec(227, "attr_227", 2.0D, 0.0D, 0), new MasterySpec(374, "attr_374", 0.0D, 1.0D, 0), new MasterySpec(80, "Base_Mana_Cost", 2.0D, 0.0D, 0) }),
            new("MasteryMultishotMultipleReload", 175, 6, new MasterySpec[] { new MasterySpec(79, "Base_Cooldown", 180.0D, 0.0D, 0), new MasterySpec(166, "Buff_Duration", 300.0D, 0.0D, 0), new MasterySpec(292, "attr_292", 0.02D, 0.0D, 0) }),
            new("MasteryMultishotFork", 471, 5, new MasterySpec[] {  }),
            new("MasteryMultishotExplosiveArrows", 473, 5, new MasterySpec[] {  }),
            new("MasteryMultishotKnockback", 475, 5, new MasterySpec[] {  }),
        },
        ["SummonWolf"] = new MasteryProfile[]
        {
            new("MasterySummonWolfSpiritWolf", 177, 10, new MasterySpec[] { new MasterySpec(79, "Base_Cooldown", 30.0D, 120.0D, 0), new MasterySpec(375, "attr_375", 1.0D, 0.0D, 0), new MasterySpec(376, "Power_SummonWolf_SpiritWolf_Stats_Multiplier", 0.1D, 0.0D, 0) }),
            new("MasterySummonWolfSpeed", 179, 1, new MasterySpec[] { new MasterySpec(1101, "Movement_Speed_Bonus_Percent", 0.15D, 0.0D, 0) }),
            new("MasterySummonWolfEnrage", 181, 5, new MasterySpec[] { new MasterySpec(79, "Base_Cooldown", 2.0D, 0.0D, 1), new MasterySpec(378, "Power_SummonWolf_More_Damage_On_Death", 0.02D, 0.0D, 0), new MasterySpec(293, "Power_SummonWolf_Death_Enrage_Duration", 2.0D, 0.0D, 0) }),
            new("MasterySummonWolfAgility", 219, 1, new MasterySpec[] { new MasterySpec(377, "attr_377", 1.0D, 0.0D, 0) }),
            new("MasterySummonWolfVigor", 267, 5, new MasterySpec[] { new MasterySpec(377, "attr_377", 1.0D, 0.0D, 0) }),
            new("MasterySummonWolfAoeAttack", 477, 5, new MasterySpec[] {  }),
            new("MasterySummonWolfReducedCooldown", 479, 5, new MasterySpec[] {  }),
        },
        ["IceNova"] = new MasteryProfile[]
        {
            new("MasteryIceNovaImprovedIceNova", 40, 1, new MasterySpec[] { new MasterySpec(58, "Base_Power_Weapon_Damage_Multiplier", 0.05D, 0.0D, 0) }),
            new("MasteryIceNovaDeepFreeze", 42, 6, new MasterySpec[] { new MasterySpec(205, "Power_Freeze_Duration", 0.5D, 0.0D, 0), new MasterySpec(193, "Base_Power_Radius", 1.0D, 0.0D, 0), new MasterySpec(79, "Base_Cooldown", 4.0D, 0.0D, 0) }),
            new("MasteryIceNovaConcentratedIce", 44, 5, new MasterySpec[] { new MasterySpec(193, "Base_Power_Radius", 0.5D, 0.0D, 1), new MasterySpec(79, "Base_Cooldown", 3.0D, 0.0D, 1) }),
            new("MasteryIceNovaFreeze", 259, 5, new MasterySpec[] { new MasterySpec(58, "Base_Power_Weapon_Damage_Multiplier", 0.05D, 0.0D, 0) }),
            new("MasteryIceNovaThaw", 509, 5, new MasterySpec[] {  }),
            new("MasteryIceNovaIceBomb", 511, 5, new MasterySpec[] {  }),
        },
        ["IceBlast"] = new MasteryProfile[]
        {
            new("MasteryIceBlastImprovedIceBlast", 34, 1, new MasterySpec[] { new MasterySpec(58, "Base_Power_Weapon_Damage_Multiplier", 0.08D, 0.0D, 0), new MasterySpec(221, "Power_Weapon_Damage_Multiplier_2", 0.05D, 0.0D, 0) }),
            new("MasteryIceBlastCounterBlast", 36, 6, new MasterySpec[] { new MasterySpec(229, "attr_229", 0.0D, 4.0D, 0), new MasterySpec(228, "Ice_Blast_Counter_Blast_Chance", 0.05D, 0.0D, 0), new MasterySpec(79, "Base_Cooldown", 30.0D, 0.0D, 0), new MasterySpec(166, "Buff_Duration", 60.0D, 0.0D, 0) }),
            new("MasteryIceBlastPiercingIce", 38, 5, new MasterySpec[] { new MasterySpec(230, "Power_Projectile_Pierce_Chance", 0.15D, 0.0D, 0), new MasterySpec(227, "attr_227", 0.0D, 3.0D, 0), new MasterySpec(79, "Base_Cooldown", 2.0D, 0.0D, 1) }),
            new("MasteryIceBlastRapidRetaliation", 513, 5, new MasterySpec[] {  }),
            new("MasteryIceBlastManaOnHit", 515, 5, new MasterySpec[] {  }),
            new("MasteryIceBlastCriticalDamage", 517, 5, new MasterySpec[] {  }),
        },
        ["InfernalBlast"] = new MasteryProfile[]
        {
            new("MasteryInfernalBlastImprovedInfernalBlast", 46, 1, new MasterySpec[] { new MasterySpec(58, "Base_Power_Weapon_Damage_Multiplier", 0.1D, 0.0D, 0), new MasterySpec(221, "Power_Weapon_Damage_Multiplier_2", 0.05D, 0.0D, 0) }),
            new("MasteryInfernalBlastConflagration", 48, 6, new MasterySpec[] { new MasterySpec(193, "Base_Power_Radius", 0.8D, 0.0D, 0), new MasterySpec(79, "Base_Cooldown", 5.0D, 0.0D, 0), new MasterySpec(232, "Power_Duration", 2.0D, 0.0D, 0) }),
            new("MasteryInfernalBlastMulticast", 50, 3, new MasterySpec[] { new MasterySpec(18, "attr_18", 1.0D, 0.0D, 0), new MasterySpec(231, "Power_Stack_Use_Cooldown", 0.0D, 2.0D, 0) }),
            new("MasteryInfernalBlastVelocity", 253, 5, new MasterySpec[] {  }),
            new("MasteryInfernalBlastMultipleExplosions", 519, 5, new MasterySpec[] {  }),
            new("MasteryInfernalBlastLivingBomb", 521, 5, new MasterySpec[] {  }),
        },
        ["Blizzard"] = new MasteryProfile[]
        {
            new("MasteryBlizzardCrystalShards", 22, 20, new MasterySpec[] { new MasterySpec(700, "Base_Crit_Chance_Multiplier", 0.1D, 0.0D, 0) }),
            new("MasteryBlizzardIcestorm", 24, 6, new MasterySpec[] { new MasterySpec(193, "Base_Power_Radius", 1.0D, 0.0D, 0), new MasterySpec(79, "Base_Cooldown", 5.0D, 0.0D, 0) }),
            new("MasteryBlizzardGravity", 26, 5, new MasterySpec[] { new MasterySpec(79, "Base_Cooldown", 3.0D, 0.0D, 1), new MasterySpec(58, "Base_Power_Weapon_Damage_Multiplier", 0.05D, 0.0D, 0) }),
            new("MasteryBlizzardChillingGround", 261, 5, new MasterySpec[] { new MasterySpec(700, "Base_Crit_Chance_Multiplier", 0.1D, 0.0D, 0) }),
            new("MasteryBlizzardRapidStorm", 523, 5, new MasterySpec[] {  }),
            new("MasteryBlizzardHurricane", 525, 5, new MasterySpec[] {  }),
        },
        ["ChainLightning"] = new MasteryProfile[]
        {
            new("MasteryChainLightningImprovedChainLightning", 10, 1, new MasterySpec[] { new MasterySpec(58, "Base_Power_Weapon_Damage_Multiplier", 0.1D, 0.0D, 0) }),
            new("MasteryChainLightningWeapon", 12, 6, new MasterySpec[] { new MasterySpec(79, "Base_Cooldown", 15.0D, 0.0D, 0) }),
            new("MasteryChainLightningChains", 14, 5, new MasterySpec[] { new MasterySpec(143, "ChainLightning_Max_Num_Chains", 1.0D, 0.0D, 0), new MasterySpec(79, "Base_Cooldown", 3.0D, 0.0D, 1) }),
            new("MasteryChainLightningManaChain", 255, 5, new MasterySpec[] { new MasterySpec(143, "ChainLightning_Max_Num_Chains", 1.0D, 0.0D, 0), new MasterySpec(79, "Base_Cooldown", 3.0D, 0.0D, 1) }),
            new("MasteryChainLightningDamagePerJump", 527, 5, new MasterySpec[] {  }),
            new("MasteryChainLightningThunderstrike", 529, 5, new MasterySpec[] {  }),
        },
        ["Thunderstrike"] = new MasteryProfile[]
        {
            new("MasteryThunderstrikeImprovedThunderstrike", 70, 1, new MasterySpec[] { new MasterySpec(58, "Base_Power_Weapon_Damage_Multiplier", 0.1D, 0.0D, 0) }),
            new("MasteryThunderstrikeShocking", 72, 5, new MasterySpec[] { new MasterySpec(79, "Base_Cooldown", 5.0D, 0.0D, 1), new MasterySpec(232, "Power_Duration", 1.0D, 0.0D, 0) }),
            new("MasteryThunderstrikeWrathOfThor", 74, 6, new MasterySpec[] { new MasterySpec(193, "Base_Power_Radius", 0.0D, 5.0D, 0), new MasterySpec(850, "Potion_More_Mana_During_Health_Potion", 0.0D, 5.0D, 0), new MasterySpec(79, "Base_Cooldown", 30.0D, 0.0D, 0), new MasterySpec(166, "Buff_Duration", 10.0D, 0.0D, 0) }),
            new("MasteryThunderstrikeFocusedLightning", 257, 5, new MasterySpec[] { new MasterySpec(79, "Base_Cooldown", 5.0D, 0.0D, 1), new MasterySpec(232, "Power_Duration", 1.0D, 0.0D, 0) }),
            new("MasteryThunderstrikeReCast", 531, 5, new MasterySpec[] { new MasterySpec(850, "Potion_More_Mana_During_Health_Potion", 0.0D, 5.0D, 0) }),
            new("MasteryThunderstrikeChainLightningOnHit", 533, 5, new MasterySpec[] {  }),
        },
        ["ManaShield"] = new MasteryProfile[]
        {
            new("MasteryManaShieldImprovedManaShield", 52, 1, new MasterySpec[] { new MasterySpec(181, "Mana_Shield_Life_Factor", 0.05D, 0.0D, 0) }),
            new("MasteryManaShieldHeavyShield", 54, 5, new MasterySpec[] { new MasterySpec(182, "Mana_Shield_Damage_Absorbtion_Factor", 0.04D, 0.0D, 0), new MasterySpec(79, "Base_Cooldown", 6.0D, 0.0D, 1) }),
            new("MasteryManaShieldRegeneration", 56, 6, new MasterySpec[] { new MasterySpec(79, "Base_Cooldown", 20.0D, 0.0D, 0), new MasterySpec(233, "Mana_Shield_Regen_Percent", 0.002D, 0.0D, 0) }),
            new("MasteryManaShieldReducedCritDamage", 535, 5, new MasterySpec[] {  }),
            new("MasteryManaShieldManaPotionEffect", 537, 5, new MasterySpec[] { new MasterySpec(181, "Mana_Shield_Life_Factor", 0.05D, 0.0D, 0) }),
            new("MasteryManaShieldMaxElementalResists", 539, 5, new MasterySpec[] {  }),
        },
        ["ElementalSeal"] = new MasteryProfile[]
        {
            new("MasteryElementalSealImprovedElementalSeal", 28, 1, new MasterySpec[] { new MasterySpec(221, "Power_Weapon_Damage_Multiplier_2", 0.02D, 0.0D, 0) }),
            new("MasteryElementalSealFireTrap", 30, 5, new MasterySpec[] { new MasterySpec(79, "Base_Cooldown", 5.0D, 0.0D, 1), new MasterySpec(193, "Base_Power_Radius", 0.5D, 0.0D, 0) }),
            new("MasteryElementalSealAura", 32, 6, new MasterySpec[] { new MasterySpec(234, "attr_234", 0.0D, 1.0D, 0), new MasterySpec(79, "Base_Cooldown", 20.0D, 0.0D, 0), new MasterySpec(232, "Power_Duration", 3.0D, 0.0D, 0) }),
            new("MasteryElementalSealRadius", 541, 5, new MasterySpec[] {  }),
            new("MasteryElementalSealMoreResistancesInside", 543, 5, new MasterySpec[] {  }),
            new("MasteryElementalSealMorePlayerDamage", 545, 5, new MasterySpec[] {  }),
        },
        ["Frenzy"] = new MasteryProfile[]
        {
            new("MasteryFrenzyFury", 102, 1, new MasterySpec[] { new MasterySpec(184, "Buff_Stack_Duration", 1.0D, 0.0D, 0) }),
            new("MasteryFrenzyDualMastery", 134, 10, new MasterySpec[] { new MasterySpec(262, "Dual_Strike_Chance_When_Dual_Wielding", 0.01D, 0.0D, 0) }),
            new("MasteryFrenzyEndlessFrenzy", 136, 6, new MasterySpec[] { new MasterySpec(79, "Base_Cooldown", 120.0D, 0.0D, 0), new MasterySpec(232, "Power_Duration", 300.0D, 0.0D, 0), new MasterySpec(451, "Attack_Speed_Bonus_Percent", 0.01D, 0.0D, 1) }),
            new("MasteryFrenzyMaxAttackSpeed", 429, 5, new MasterySpec[] {  }),
            new("MasteryFrenzyEstablishedWeakness", 431, 5, new MasterySpec[] {  }),
            new("MasteryFrenzyDualStriking", 433, 5, new MasterySpec[] {  }),
        },
        ["Intimidate"] = new MasteryProfile[]
        {
            new("MasteryIntimidateSubdue", 106, 10, new MasterySpec[] { new MasterySpec(1404, "Weapon_Fire_Damage_Bonus_Percent", 0.01D, 0.0D, 1), new MasterySpec(1504, "Weapon_Cold_Damage_Bonus_Percent", 0.01D, 0.0D, 1), new MasterySpec(1604, "Weapon_Lightning_Damage_Bonus_Percent", 0.01D, 0.0D, 1), new MasterySpec(1704, "Weapon_Poison_Damage_Bonus_Percent", 0.01D, 0.0D, 1), new MasterySpec(504, "Weapon_Physical_Damage_Bonus_Percent", 0.01D, 0.0D, 1) }),
            new("MasteryIntimidateIntimidatingPresence", 108, 6, new MasterySpec[] { new MasterySpec(504, "Weapon_Physical_Damage_Bonus_Percent", 0.02D, 0.0D, 0), new MasterySpec(1404, "Weapon_Fire_Damage_Bonus_Percent", 0.02D, 0.0D, 0), new MasterySpec(1504, "Weapon_Cold_Damage_Bonus_Percent", 0.02D, 0.0D, 0), new MasterySpec(1604, "Weapon_Lightning_Damage_Bonus_Percent", 0.02D, 0.0D, 0), new MasterySpec(1704, "Weapon_Poison_Damage_Bonus_Percent", 0.02D, 0.0D, 0), new MasterySpec(79, "Base_Cooldown", 150.0D, 0.0D, 0), new MasterySpec(263, "Intimidate_Aura_Radius", 0.0D, 1.0D, 0), new MasterySpec(193, "Base_Power_Radius", 2.0D, 0.0D, 0) }),
            new("MasteryIntimidateShieldUp", 110, 5, new MasterySpec[] {  }),
            new("MasteryIntimidateMock", 435, 5, new MasterySpec[] {  }),
            new("MasteryIntimidateWound", 437, 5, new MasterySpec[] {  }),
            new("MasteryIntimidateShieldWall", 439, 5, new MasterySpec[] {  }),
        },
        ["Pounce"] = new MasteryProfile[]
        {
            new("MasteryPounceKnockback", 112, 5, new MasterySpec[] { new MasterySpec(267, "Knockback_Magnitude", 0.5D, 0.0D, 0), new MasterySpec(58, "Base_Power_Weapon_Damage_Multiplier", 0.03D, 0.0D, 0) }),
            new("MasteryPounceProwess", 138, 6, new MasterySpec[] { new MasterySpec(264, "Pounce_Auto_Jump_Radius", 1.5D, 0.0D, 0), new MasterySpec(850, "Potion_More_Mana_During_Health_Potion", -2.0D, 20.0D, 0), new MasterySpec(232, "Power_Duration", 120.0D, 0.0D, 0), new MasterySpec(79, "Base_Cooldown", 90.0D, 0.0D, 0), new MasterySpec(58, "Base_Power_Weapon_Damage_Multiplier", 0.03D, 0.0D, 1) }),
            new("MasteryPounceImprovedPounce", 140, 1, new MasterySpec[] { new MasterySpec(22, "Local_Base_Stun_Chance", 0.01D, 0.0D, 0) }),
            new("MasteryPounceLongjump", 229, 5, new MasterySpec[] { new MasterySpec(850, "Potion_More_Mana_During_Health_Potion", -2.0D, 20.0D, 0) }),
            new("MasteryPounceWings", 233, 10, new MasterySpec[] {  }),
            new("MasteryPounceRend", 441, 5, new MasterySpec[] {  }),
        },
        ["ImpalingTrap"] = new MasteryProfile[]
        {
            new("MasteryImpalingTrapPoisonedEdges", 189, 5, new MasterySpec[] { new MasterySpec(79, "Base_Cooldown", 3.0D, 0.0D, 1), new MasterySpec(380, "Power_Impaling_Trap_Poisoned_Edges_Slow_Effect", 0.1D, 0.0D, 0), new MasterySpec(166, "Buff_Duration", 1.0D, 0.0D, 0) }),
            new("MasteryImpalingTrapSteelSpikes", 191, 10, new MasterySpec[] { new MasterySpec(717, "Armor_Piercing_Percent", 0.02D, 0.0D, 0) }),
            new("MasteryImpalingTrapDeviousTrap", 193, 6, new MasterySpec[] { new MasterySpec(79, "Base_Cooldown", 180.0D, 0.0D, 0), new MasterySpec(379, "Power_Backflip_Chance_To_Cast_Impaling_Trap", 0.1D, 0.0D, 0), new MasterySpec(166, "Buff_Duration", 180.0D, 0.0D, 0) }),
            new("MasteryImpalingTrapFreeze", 481, 5, new MasterySpec[] {  }),
            new("MasteryImpalingTrapHealingTrap", 483, 5, new MasterySpec[] {  }),
            new("MasteryImpalingTrapFireBomb", 485, 5, new MasterySpec[] {  }),
        },
        ["MarkOfTheChosen"] = new MasteryProfile[]
        {
            new("MasteryMarkOfTheChosenPenetrate", 183, 5, new MasterySpec[] { new MasterySpec(79, "Base_Cooldown", 3.0D, 0.0D, 1), new MasterySpec(253, "attr_253", -0.02D, 0.0D, 1) }),
            new("MasteryMarkOfTheChosenMarkedForDeath", 185, 1, new MasterySpec[] { new MasterySpec(6, "Amplify_Damage_Taken_Percent", 0.005D, 0.0D, 0) }),
            new("MasteryMarkOfTheChosenAutoMark", 187, 6, new MasterySpec[] { new MasterySpec(79, "Base_Cooldown", 120.0D, 0.0D, 0), new MasterySpec(232, "Power_Duration", 240.0D, 0.0D, 0), new MasterySpec(381, "Power_Mark_Of_The_Chosen_Auto_Mark_Min_Combat_Duration", -1.0D, 8.0D, 0), new MasterySpec(6, "Amplify_Damage_Taken_Percent", 0.01D, 0.0D, 1) }),
            new("MasteryMarkOfTheChosenCull", 487, 5, new MasterySpec[] {  }),
            new("MasteryMarkOfTheChosenLessResistances", 489, 5, new MasterySpec[] {  }),
            new("MasteryMarkOfTheChosenDoom", 491, 5, new MasterySpec[] {  }),
        },
        ["Tornado"] = new MasteryProfile[]
        {
            new("MasteryTornadoImprovedTornado", 76, 1, new MasterySpec[] { new MasterySpec(58, "Base_Power_Weapon_Damage_Multiplier", 0.05D, 0.0D, 0) }),
            new("MasteryTornadoSeeker", 78, 1, new MasterySpec[] { new MasterySpec(235, "attr_235", 0.0D, 1.0D, 0), new MasterySpec(193, "Base_Power_Radius", 0.3D, 0.0D, 0), new MasterySpec(232, "Power_Duration", 5.0D, 0.0D, 0), new MasterySpec(79, "Base_Cooldown", 20.0D, 0.0D, 0) }),
            new("MasteryTornadoAttraction", 80, 5, new MasterySpec[] { new MasterySpec(236, "MaceSpecialization_Throw_Mace_Radius", 0.0D, 1.0D, 0), new MasterySpec(237, "Tornado_Attract_Radius", 0.0D, 2.0D, 0), new MasterySpec(238, "attr_238", 3.0D, 0.0D, 0) }),
            new("MasteryTornadoAutoCast", 263, 6, new MasterySpec[] { new MasterySpec(235, "attr_235", 0.0D, 1.0D, 0), new MasterySpec(193, "Base_Power_Radius", 0.3D, 0.0D, 0), new MasterySpec(232, "Power_Duration", 5.0D, 0.0D, 0), new MasterySpec(79, "Base_Cooldown", 20.0D, 0.0D, 0) }),
            new("MasteryTornadoTwister", 265, 5, new MasterySpec[] { new MasterySpec(58, "Base_Power_Weapon_Damage_Multiplier", 0.05D, 0.0D, 0) }),
            new("MasteryTornadoHurricane", 547, 5, new MasterySpec[] {  }),
        },
        ["Slam"] = new MasteryProfile[]
        {
            new("MasterySlamImprovedSlam", 114, 1, new MasterySpec[] {  }),
            new("MasterySlamWideSlam", 116, 5, new MasterySpec[] { new MasterySpec(193, "Base_Power_Radius", 0.1D, 0.0D, 0) }),
            new("MasterySlamEarthquake", 142, 6, new MasterySpec[] {  }),
            new("MasterySlamQuickSlam", 231, 10, new MasterySpec[] {  }),
            new("MasterySlamShockwave", 281, 2, new MasterySpec[] {  }),
            new("MasterySlamVampiricSlam", 443, 5, new MasterySpec[] {  }),
            new("MasterySlamMana", 445, 5, new MasterySpec[] {  }),
        },
        ["ManaArrows"] = new MasteryProfile[]
        {
            new("MasteryManaArrowsDrainingArrows", 195, 6, new MasterySpec[] { new MasterySpec(79, "Base_Cooldown", 90.0D, 0.0D, 0), new MasterySpec(382, "Power_Mana_Arrows_Drain_Mana_Per_Second", 20.0D, 10.0D, 0), new MasterySpec(383, "Power_Mana_Arrows_Drain_More_Damage_Bonus", 0.05D, 0.0D, 0), new MasterySpec(232, "Power_Duration", 120.0D, 0.0D, 0) }),
            new("MasteryManaArrowsImprovedManaArrows", 203, 1, new MasterySpec[] { new MasterySpec(384, "Power_Mana_Arrows_Mana_Per_Hit", 1.0D, 0.0D, 0) }),
            new("MasteryManaArrowsQuickRecharge", 211, 5, new MasterySpec[] { new MasterySpec(58, "Base_Power_Weapon_Damage_Multiplier", 0.15D, 0.0D, 1), new MasterySpec(79, "Base_Cooldown", 4.0D, 0.0D, 1) }),
            new("MasteryManaArrowsCharges", 249, 10, new MasterySpec[] { new MasterySpec(384, "Power_Mana_Arrows_Mana_Per_Hit", 1.0D, 0.0D, 0) }),
            new("MasteryManaArrowsManaOnKill", 493, 5, new MasterySpec[] {  }),
            new("MasteryManaArrowsMaxMana", 495, 5, new MasterySpec[] {  }),
        },
        ["Thorns"] = new MasteryProfile[]
        {
            new("MasteryThornsThickThorns", 197, 6, new MasterySpec[] { new MasterySpec(79, "Base_Cooldown", 90.0D, 0.0D, 0), new MasterySpec(166, "Buff_Duration", 240.0D, 0.0D, 0), new MasterySpec(179, "Reflect_Melee_Damage_Percent", 0.4D, 0.0D, 1), new MasterySpec(271, "Base_Physical_Damage_Reduction_Bonus", 0.01D, 0.0D, 0) }),
            new("MasteryThornsRazorEdges", 205, 10, new MasterySpec[] { new MasterySpec(179, "Reflect_Melee_Damage_Percent", 0.1D, 0.0D, 0) }),
            new("MasteryThornsDeepCuts", 213, 5, new MasterySpec[] { new MasterySpec(79, "Base_Cooldown", 4.0D, 0.0D, 1), new MasterySpec(385, "Power_Thorns_Bleed_Damage_Percent", 0.02D, 0.0D, 0) }),
            new("MasteryThornsThornArmor", 251, 5, new MasterySpec[] { new MasterySpec(179, "Reflect_Melee_Damage_Percent", 0.1D, 0.0D, 0) }),
            new("MasteryThornsToxicSting", 497, 5, new MasterySpec[] {  }),
            new("MasteryThornsCritDamageReduction", 499, 5, new MasterySpec[] {  }),
        },
        ["BeastWithin"] = new MasteryProfile[]
        {
            new("MasteryBeastWithinHemoglobin", 199, 1, new MasterySpec[] { new MasterySpec(79, "Base_Cooldown", 600.0D, 0.0D, 0), new MasterySpec(66, "attr_66", 1.0D, 0.0D, 0), new MasterySpec(166, "Buff_Duration", 1200.0D, 0.0D, 0), new MasterySpec(307, "attr_307", -0.9D, 0.0D, 0) }),
            new("MasteryBeastWithinBearsStrength", 207, 1, new MasterySpec[] { new MasterySpec(109, "Strength_Bonus_Percent", 0.1D, 0.0D, 0) }),
            new("MasteryBeastWithinVoracity", 215, 5, new MasterySpec[] { new MasterySpec(340, "Life_Leech_Rate_Bonus_Percent", 0.06D, 0.0D, 0), new MasterySpec(79, "Base_Cooldown", 3.0D, 0.0D, 1) }),
            new("MasteryBeastWithinDuration", 247, 6, new MasterySpec[] { new MasterySpec(79, "Base_Cooldown", 600.0D, 0.0D, 0), new MasterySpec(66, "attr_66", 1.0D, 0.0D, 0), new MasterySpec(166, "Buff_Duration", 1200.0D, 0.0D, 0), new MasterySpec(307, "attr_307", -0.9D, 0.0D, 0) }),
            new("MasteryBeastWithinSnakesDexterity", 501, 5, new MasterySpec[] {  }),
            new("MasteryBeastWithinTotalLeech", 503, 5, new MasterySpec[] {  }),
        },
        ["FrozenArrow"] = new MasteryProfile[]
        {
            new("MasteryFrozenArrowRapidFreeze", 201, 5, new MasterySpec[] { new MasterySpec(79, "Base_Cooldown", 3.0D, 0.0D, 1), new MasterySpec(193, "Base_Power_Radius", 0.5D, 0.0D, 1) }),
            new("MasteryFrozenArrowCrystallize", 209, 20, new MasterySpec[] { new MasterySpec(387, "Power_Frozen_Arrow_Slow_Attacks_Percent", 0.02D, 0.0D, 0), new MasterySpec(388, "Power_Frozen_Arrow_Slow_Attacks_Duration", 0.0D, 10.0D, 0) }),
            new("MasteryFrozenArrowAutoFreeze", 217, 6, new MasterySpec[] { new MasterySpec(79, "Base_Cooldown", 20.0D, 0.0D, 0) }),
            new("MasteryFrozenArrowFrozenWave", 245, 5, new MasterySpec[] { new MasterySpec(79, "Base_Cooldown", 20.0D, 0.0D, 0) }),
            new("MasteryFrozenArrowFrozenShots", 505, 5, new MasterySpec[] {  }),
            new("MasteryFrozenArrowPiercingIce", 507, 5, new MasterySpec[] {  }),
        },
        ["PoisonCloud"] = new MasteryProfile[]
        {
            new("MasteryPoisonCloudSlime", 58, 10, new MasterySpec[] { new MasterySpec(239, "Power_Slow_Effect_Percent", 0.03D, 0.0D, 0) }),
            new("MasteryPoisonCloudDisease", 60, 5, new MasterySpec[] { new MasterySpec(79, "Base_Cooldown", 10.0D, 10.0D, 0), new MasterySpec(240, "Poison_Cloud_Spread_Radius", 0.4D, 1.0D, 0) }),
            new("MasteryPoisonCloudDecay", 62, 5, new MasterySpec[] { new MasterySpec(79, "Base_Cooldown", 6.0D, 0.0D, 1), new MasterySpec(58, "Base_Power_Weapon_Damage_Multiplier", 0.2D, 0.0D, 0) }),
            new("MasteryPoisonCloudAutoCast", 549, 6, new MasterySpec[] {  }),
            new("MasteryPoisonCloudSlimelings", 551, 5, new MasterySpec[] {  }),
            new("MasteryPoisonCloudHeal", 553, 5, new MasterySpec[] {  }),
        },
        ["Teleport"] = new MasteryProfile[]
        {
            new("MasteryTeleportImprovedTeleport", 64, 5, new MasterySpec[] { new MasterySpec(80, "Base_Mana_Cost", 4.0D, 0.0D, 1) }),
            new("MasteryTeleportElusiveness", 66, 5, new MasterySpec[] { new MasterySpec(166, "Buff_Duration", 20.0D, 0.0D, 0), new MasterySpec(801, "Dodge_Chance_Bonus_Percent", 0.0D, 0.1D, 0), new MasterySpec(79, "Base_Cooldown", 10.0D, 0.0D, 0) }),
            new("MasteryTeleportRecitement", 68, 5, new MasterySpec[] { new MasterySpec(166, "Buff_Duration", 1.0D, 0.0D, 0), new MasterySpec(58, "Base_Power_Weapon_Damage_Multiplier", 0.0D, 0.15D, 0) }),
            new("MasteryTeleportSafetyTeleport", 555, 6, new MasterySpec[] {  }),
            new("MasteryTeleportLightningSpeed", 557, 5, new MasterySpec[] {  }),
            new("MasteryTeleportKnockback", 559, 5, new MasterySpec[] {  }),
        },
        ["Mixology"] = new MasteryProfile[]
        {
            new("MasteryMixologyDuration", 269, 1, new MasterySpec[] {  }),
            new("MasteryMixologyAutoPotion", 271, 10, new MasterySpec[] {  }),
            new("MasteryMixologyPowerfulConcotion", 273, 5, new MasterySpec[] {  }),
            new("MasteryMixologyThirst", 275, 5, new MasterySpec[] {  }),
            new("MasteryMixologySmartPotions", 277, 1, new MasterySpec[] {  }),
            new("MasteryMixologyManaDuringLife", 395, 5, new MasterySpec[] {  }),
            new("MasteryMixologyLifeDuringMana", 397, 5, new MasterySpec[] {  }),
        },
        ["SummonSkeleton"] = new MasteryProfile[]
        {
            new("MasterySummonSkeletonImprovedSkeletons", 283, 10, new MasterySpec[] {  }),
            new("MasterySummonSkeletonAutoSummon", 305, 6, new MasterySpec[] {  }),
            new("MasterySummonSkeletonSkeletalArmy", 327, 4, new MasterySpec[] {  }),
            new("MasterySummonSkeletonDurableBones", 351, 5, new MasterySpec[] {  }),
            new("MasterySummonSkeletonMoreArmor", 561, 5, new MasterySpec[] {  }),
            new("MasterySummonSkeletonDetonate", 563, 5, new MasterySpec[] {  }),
        },
        ["SummonDemon"] = new MasteryProfile[]
        {
            new("MasterySummonDemonImprovedDemons", 285, 10, new MasterySpec[] {  }),
            new("MasterySummonDemonAutoSummon", 307, 6, new MasterySpec[] {  }),
            new("MasterySummonDemonDemonicHorde", 329, 4, new MasterySpec[] {  }),
            new("MasterySummonDemonSharpshooter", 353, 5, new MasterySpec[] {  }),
            new("MasterySummonDemonReducedRangedDamageTaken", 565, 5, new MasterySpec[] {  }),
            new("MasterySummonDemonMoreDamageDealtAndTaken", 567, 5, new MasterySpec[] {  }),
        },
        ["SummonDeath"] = new MasteryProfile[]
        {
            new("MasterySummonDeathImprovedDeath", 287, 10, new MasterySpec[] {  }),
            new("MasterySummonDeathAutoSummon", 309, 6, new MasterySpec[] {  }),
            new("MasterySummonDeathAttackSpeed", 331, 5, new MasterySpec[] {  }),
            new("MasterySummonDeathSweep", 355, 5, new MasterySpec[] {  }),
            new("MasterySummonDeathDuo", 357, 1, new MasterySpec[] {  }),
            new("MasterySummonDeathChanceToBlock", 569, 5, new MasterySpec[] {  }),
            new("MasterySummonDeathMoreInitialDamage", 571, 5, new MasterySpec[] {  }),
        },
        ["UnholyFocus"] = new MasteryProfile[]
        {
            new("MasteryUnholyFocusUnholySpeed", 289, 10, new MasterySpec[] {  }),
            new("MasteryUnholyFocusAutocast", 311, 6, new MasterySpec[] {  }),
            new("MasteryUnholyFocusProminence", 333, 5, new MasterySpec[] {  }),
            new("MasteryUnholyFocusFocusedMind", 359, 5, new MasterySpec[] {  }),
            new("MasteryUnholyFocusChargeCooldown", 573, 5, new MasterySpec[] {  }),
            new("MasteryUnholyFocusShadowboltDamage", 575, 5, new MasterySpec[] {  }),
            new("MasteryUnholyFocusMaxAttackSpeed", 577, 5, new MasterySpec[] {  }),
        },
        ["Shadowbolt"] = new MasteryProfile[]
        {
            new("MasteryShadowboltImprovedShadowbolt", 291, 1, new MasterySpec[] {  }),
            new("MasteryShadowboltAutoCast", 313, 6, new MasterySpec[] {  }),
            new("MasteryShadowboltShadowPower", 335, 5, new MasterySpec[] {  }),
            new("MasteryShadowboltExplosion", 363, 5, new MasterySpec[] {  }),
            new("MasteryShadowboltSpeed", 389, 5, new MasterySpec[] {  }),
            new("MasteryShadowboltPenetration", 579, 5, new MasterySpec[] {  }),
            new("MasteryShadowboltCooldown", 581, 5, new MasterySpec[] {  }),
        },
        ["DrainLife"] = new MasteryProfile[]
        {
            new("MasteryDrainLifeImprovedDrainLife", 293, 10, new MasterySpec[] {  }),
            new("MasteryDrainLifeAutocast", 315, 6, new MasterySpec[] {  }),
            new("MasteryDrainLifeEndlessDrain", 337, 5, new MasterySpec[] {  }),
            new("MasteryDrainLifeSoulDrain", 365, 5, new MasterySpec[] {  }),
            new("MasteryDrainLifeSoulTransfer", 367, 5, new MasterySpec[] {  }),
            new("MasteryDrainLifeRange", 583, 5, new MasterySpec[] {  }),
        },
        ["DemonicPresence"] = new MasteryProfile[]
        {
            new("MasteryDemonicPresenceImprovedDemonicPresence", 295, 10, new MasterySpec[] {  }),
            new("MasteryDemonicPresenceAura", 317, 6, new MasterySpec[] {  }),
            new("MasteryDemonicPresenceCower", 339, 5, new MasterySpec[] {  }),
            new("MasteryDemonicPresenceRegeneration", 369, 5, new MasterySpec[] {  }),
            new("MasteryDemonicPresenceMoreDefenses", 585, 5, new MasterySpec[] {  }),
            new("MasteryDemonicPresencePotionEffects", 587, 5, new MasterySpec[] {  }),
        },
        ["Decay"] = new MasteryProfile[]
        {
            new("MasteryDecayImprovedDecay", 297, 10, new MasterySpec[] {  }),
            new("MasteryDecayAutocast", 319, 6, new MasterySpec[] {  }),
            new("MasteryDecayRot", 341, 5, new MasterySpec[] {  }),
            new("MasteryDecayDuration", 371, 5, new MasterySpec[] {  }),
            new("MasteryDecayMorePoisonDamageTaken", 589, 5, new MasterySpec[] {  }),
            new("MasteryDecayMinionRegen", 591, 5, new MasterySpec[] {  }),
        },
        ["Sacrifice"] = new MasteryProfile[]
        {
            new("MasterySacrificeImprovedSacrifice", 299, 10, new MasterySpec[] {  }),
            new("MasterySacrificeAutoSacrifice", 321, 6, new MasterySpec[] {  }),
            new("MasterySacrificeInfusion", 343, 5, new MasterySpec[] {  }),
            new("MasterySacrificeDuration", 373, 5, new MasterySpec[] {  }),
            new("MasterySacrificeCulling", 375, 5, new MasterySpec[] {  }),
            new("MasterySacrificeDetonate", 593, 5, new MasterySpec[] {  }),
        },
        ["BoneLink"] = new MasteryProfile[]
        {
            new("MasteryBoneLinkImprovedLink", 301, 10, new MasterySpec[] {  }),
            new("MasteryBoneLinkDeepLink", 325, 6, new MasterySpec[] {  }),
            new("MasteryBoneLinkReflectiveBones", 345, 5, new MasterySpec[] {  }),
            new("MasteryBoneLinkMoreLinkedTargets", 595, 5, new MasterySpec[] {  }),
            new("MasteryBoneLinkGainLifePercentOnKill", 597, 5, new MasterySpec[] {  }),
            new("MasteryBoneLinkMoreDamageDealt", 599, 5, new MasterySpec[] {  }),
        },
        ["AstralWalk"] = new MasteryProfile[]
        {
            new("MasteryAstralWalkImprovedAstralWalk", 303, 10, new MasterySpec[] {  }),
            new("MasteryAstralWalkAutoWalk", 323, 6, new MasterySpec[] {  }),
            new("MasteryAstralWalkFlight", 347, 5, new MasterySpec[] {  }),
            new("MasteryAstralWalkDecoy", 377, 1, new MasterySpec[] {  }),
            new("MasteryAstralWalkReducedManaCost", 601, 5, new MasterySpec[] {  }),
            new("MasteryAstralWalkImmortal", 603, 5, new MasterySpec[] {  }),
        },
        ["Whirlwind"] = new MasteryProfile[]
        {
            new("MasteryWhirlwindImprovedWhirlwind", 379, 10, new MasterySpec[] {  }),
            new("MasteryWhirlwindBloodWhirl", 381, 5, new MasterySpec[] {  }),
            new("MasteryWhirlwindAutoWhirl", 383, 6, new MasterySpec[] {  }),
            new("MasteryWhirlwindJaggedBlades", 385, 5, new MasterySpec[] {  }),
            new("MasteryWhirlwindSmartWhirl", 387, 5, new MasterySpec[] {  }),
            new("MasteryWhirlwindBloodWhirlpool", 447, 5, new MasterySpec[] {  }),
        },
    };
}
