// <auto-generated> MagicOnion service stubs. Replace bodies as needed. </auto-generated>
#nullable disable
using MagicOnion;
using MagicOnion.Server;
using SharedNet.Api;
using Nordicandia.Server.State;

namespace Nordicandia.Server.Services;

public sealed class CatalogServiceApiImpl : ServiceBase<ICatalogServiceApi>, ICatalogServiceApi
{
    public MagicOnion.UnaryResult<SharedNet.Api.GetCatalogResponse> GetCatalog(SharedNet.Api.GetCatalogRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.GetCatalogResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.PurchaseCatalogItemResponse> PurchaseCatalogItem(SharedNet.Api.PurchaseCatalogItemRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.PurchaseCatalogItemResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.PurchaseCatalogItemForSilverResponse> PurchaseCatalogItemForSilver(SharedNet.Api.PurchaseCatalogItemRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.PurchaseCatalogItemForSilverResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.TradeWithMerchantResponse> TradeWithMerchant(SharedNet.Api.TradeWithMerchantRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.TradeWithMerchantResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.GenerateSetItemMerchantOffersResponse> ViewSetItemMerchantOffers(SharedNet.Api.GenerateSetItemMerchantOffersRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.GenerateSetItemMerchantOffersResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.TradeWithSetItemMerchantResponse> TradeWithSetItemMerchant(SharedNet.Api.TradeWithSetItemMerchantRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.TradeWithSetItemMerchantResponse>());
}

public sealed class ChannelServiceApiImpl : ServiceBase<IChannelServiceApi>, IChannelServiceApi
{
    public MagicOnion.UnaryResult<SharedNet.Api.ListChannelMessageListResponse> ListChannelMessages(SharedNet.Api.ListChannelMessageListRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.ListChannelMessageListResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.ReportPlayerResponse> ReportPlayer(SharedNet.Api.ReportPlayerRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.ReportPlayerResponse>());
}

public sealed class CharacterGameEventServiceApiImpl : ServiceBase<ICharacterGameEventServiceApi>, ICharacterGameEventServiceApi
{
    public MagicOnion.UnaryResult<SharedNet.Api.CharacterDiedResponse> OnCharacterDied(SharedNet.Api.CharacterDiedRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.CharacterDiedResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.CharacterDungeonRunStartedResponse> OnDungeonRunStarted(SharedNet.Api.CharacterDungeonRunStartedRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.CharacterDungeonRunStartedResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.CharacterDungeonRunCompletedResponse> OnDungeonRunCompleted(SharedNet.Api.CharacterDungeonRunCompletedRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.CharacterDungeonRunCompletedResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.CharacterGolemGameModeEndedResponse> OnGolemGameModeEnded(SharedNet.Api.CharacterGolemGameModeEndedRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.CharacterGolemGameModeEndedResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.CharacterNiflheimStartedResponse> OnNiflheimStarted(SharedNet.Api.CharacterNiflheimStartedRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.CharacterNiflheimStartedResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.CharacterNiflheimCompletedResponse> OnNiflheimCompleted(SharedNet.Api.CharacterNiflheimCompletedRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.CharacterNiflheimCompletedResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.CharacterHelheimStartedResponse> OnHelheimStarted(SharedNet.Api.CharacterHelheimStartedRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.CharacterHelheimStartedResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.CharacterHelheimCompletedResponse> OnHelheimCompleted(SharedNet.Api.CharacterHelheimCompletedRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.CharacterHelheimCompletedResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.CharacterOdrsTrailStartedResponse> OnOdrsTrailStarted(SharedNet.Api.CharacterOdrsTrailStartedRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.CharacterOdrsTrailStartedResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.CharacterOdrsTrailCompletedResponse> OnOdrsTrailCompleted(SharedNet.Api.CharacterOdrsTrailCompletedRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.CharacterOdrsTrailCompletedResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.CharacterVanaheimStartedResponse> OnVanaheimStarted(SharedNet.Api.CharacterVanaheimStartedRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.CharacterVanaheimStartedResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.CharacterVanaheimCompletedResponse> OnVanaheimCompleted(SharedNet.Api.CharacterVanaheimCompletedRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.CharacterVanaheimCompletedResponse>());
}

public sealed class CharacterPowerServiceApiImpl : ServiceBase<ICharacterPowerServiceApi>, ICharacterPowerServiceApi
{
    public MagicOnion.UnaryResult<SharedNet.Api.AssignCharacterActiveSkillResponse> AssignActiveSkill(SharedNet.Api.AssignCharacterActiveSkillRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.AssignCharacterActiveSkillResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.AssignCharacterPassiveSkillResponse> AssignPassiveSkill(SharedNet.Api.AssignCharacterPassiveSkillRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.AssignCharacterPassiveSkillResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.AssignCharacterPassiveSkillTrainingResponse> AssignPassiveSkillTraining(SharedNet.Api.AssignCharacterPassiveSkillTrainingRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.AssignCharacterPassiveSkillTrainingResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.LevelUpCharacterSkillMasteryResponse> LevelUpSkillMastery(SharedNet.Api.LevelUpCharacterSkillMasteryRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.LevelUpCharacterSkillMasteryResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.ResetCharacterSkillMasteryTreeResponse> ResetSkillMastery(SharedNet.Api.ResetCharacterSkillMasteryTreeRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.ResetCharacterSkillMasteryTreeResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.ResetAllCharacterSkillMasteryTreesResponse> ResetAllSkillMasteries(SharedNet.Api.ResetAllCharacterSkillMasteryTreesRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.ResetAllCharacterSkillMasteryTreesResponse>());
}

public sealed class CharacterServiceApiImpl : ServiceBase<ICharacterServiceApi>, ICharacterServiceApi
{
    public MagicOnion.UnaryResult<SharedNet.Api.CreateCharacterResponse> CreateCharacter(SharedNet.Api.CreateCharacterRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.CreateCharacterResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.DeleteCharacterResponse> DeleteCharacter(SharedNet.Api.DeleteCharacterRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.DeleteCharacterResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.GetCharacterListResponse> GetCharacterList(SharedNet.Api.GetCharacterListRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.GetCharacterListResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.EnterGameWithCharacterResponse> EnterGameWithCharacter(SharedNet.Api.EnterGameWithCharacterRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.EnterGameWithCharacterResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.AllocateCharacterAttributesResponse> AllocateCharacterAttributes(SharedNet.Api.AllocateCharacterAttributesRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.AllocateCharacterAttributesResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.ClaimCharacterOfflineRewardsResponse> ClaimCharacterOfflineRewards(SharedNet.Api.ClaimCharacterOfflineRewardsRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.ClaimCharacterOfflineRewardsResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.ClaimRegularChristmasItemResponse> ClaimRegularChristmasItem(SharedNet.Api.ClaimRegularChristmasItemRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.ClaimRegularChristmasItemResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.ClaimAdChristmasItemResponse> ClaimAdChristmasItem(SharedNet.Api.ClaimAdChristmasItemRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.ClaimAdChristmasItemResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.InitializeRegularChristmasRewardsResponse> InitializeRegularChristmasRewards(SharedNet.Api.InitializeRegularChristmasRewardsRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.InitializeRegularChristmasRewardsResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.InitializeAdChristmasRewardsResponse> InitializeAdChristmasRewards(SharedNet.Api.InitializeAdChristmasRewardsRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.InitializeAdChristmasRewardsResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.GetGiftStateResponse> GetGiftState(SharedNet.Api.GetGiftStateRequest request) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.GetGiftStateResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.ClaimGiftResponse> ClaimGift(SharedNet.Api.ClaimGiftRequest request) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.ClaimGiftResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.ResurrectCharacterResponse> ResurrectCharacter(SharedNet.Api.ResurrectCharacterRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.ResurrectCharacterResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.ResetCharacterAttributesResponse> ResetCharacterAttributes(SharedNet.Api.ResetCharacterAttributesRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.ResetCharacterAttributesResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.ExpandCharacterStashPageResponse> ExpandCharacterStashPage(SharedNet.Api.ExpandCharacterStashPageRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.ExpandCharacterStashPageResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.ExpandCharacterInventoryRowResponse> ExpandCharacterInventoryRow(SharedNet.Api.ExpandCharacterInventoryRowRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.ExpandCharacterInventoryRowResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.ExpandCharacterSkillSlotsResponse> ExpandCharacterSkillSlots(SharedNet.Api.ExpandCharacterSkillSlotsRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.ExpandCharacterSkillSlotsResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.UpdateItemFilterResponse> UpdateItemFilter(SharedNet.Api.UpdateItemFilterRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.UpdateItemFilterResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.UpdateCharacterSettingsResponse> UpdateCharacterSettings(SharedNet.Api.UpdateCharacterSettingsRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.UpdateCharacterSettingsResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.UpdateCharacterOnlineStatusResponse> UpdateCharacterOnlineStatus(SharedNet.Api.UpdateCharacterOnlineStatusRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.UpdateCharacterOnlineStatusResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.UpdateAvatarResponse> UpdateAvatar(SharedNet.Api.UpdateAvatarRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.UpdateAvatarResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.UpdatePetResponse> UpdatePet(SharedNet.Api.UpdatePetRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.UpdatePetResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.UnlockPetResponse> UnlockPet(SharedNet.Api.UnlockPetRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.UnlockPetResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.UpdateCombatPetResponse> UpdateCombatPet(SharedNet.Api.UpdateCombatPetRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.UpdateCombatPetResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.UnlockCombatPetResponse> UnlockCombatPet(SharedNet.Api.UnlockCombatPetRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.UnlockCombatPetResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.CheckCombatPetStateResponse> CheckCombatPetState(SharedNet.Api.CheckCombatPetStateRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.CheckCombatPetStateResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.OnCombatPetAdWatchResponse> OnCombatPetAdWatch(SharedNet.Api.OnCombatPetAdWatchRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.OnCombatPetAdWatchResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.ResurrectCombatPetResponse> ResurrectCombatPet(SharedNet.Api.ResurrectCombatPetRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.ResurrectCombatPetResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.OnPetDiedResponse> OnPetDied(SharedNet.Api.OnPetDiedRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.OnPetDiedResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.OnPetExpPotionConsumedResponse> OnPetExpPotionConsumed(SharedNet.Api.OnPetExpPotionConsumedRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.OnPetExpPotionConsumedResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.ChangeRaceResponse> ChangeRace(SharedNet.Api.ChangeRaceRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.ChangeRaceResponse>());
}

public sealed class GameModeServiceApiImpl : ServiceBase<IGameModeServiceApi>, IGameModeServiceApi
{
    public MagicOnion.UnaryResult<SharedNet.Api.GetSeasonInfoResponse> GetSeasonInfo(SharedNet.Api.GetSeasonInfoRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.GetSeasonInfoResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.ClaimSeasonRewardResponse> ClaimSeasonReward(SharedNet.Api.ClaimSeasonRewardRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.ClaimSeasonRewardResponse>());
}

public sealed class GameModeUserServiceApiImpl : ServiceBase<IGameModeUserServiceApi>, IGameModeUserServiceApi
{
    public MagicOnion.UnaryResult<SharedNet.Api.ExpandGameModeUserStashPageResponse> ExpandGameModeUserStashPage(SharedNet.Api.ExpandGameModeUserStashPageRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.ExpandGameModeUserStashPageResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.UpgradeGameModeStashPageResponse> UpgradeGameModeStashPage(SharedNet.Api.UpgradeGameModeStashPageRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.UpgradeGameModeStashPageResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.UpdateGameModeStashPageSettingsResponse> UpdateGameModeStashPageSettings(SharedNet.Api.UpdateGameModeStashPageSettingsRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.UpdateGameModeStashPageSettingsResponse>());
}

public sealed class GuildServiceApiImpl : ServiceBase<IGuildServiceApi>, IGuildServiceApi
{
    public MagicOnion.UnaryResult<SharedNet.Api.CreateGuildResponse> CreateGuild(SharedNet.Api.CreateGuildRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.CreateGuildResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.FindGuildsResponse> FindGuilds(SharedNet.Api.FindGuildsRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.FindGuildsResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.GetGuildDetailsResponse> GetGuildDetails(SharedNet.Api.GetGuildDetailsRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.GetGuildDetailsResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.EditGuildResponse> EditGuild(SharedNet.Api.EditGuildRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.EditGuildResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.DisbandGuildResponse> DisbandGuild(SharedNet.Api.DisbandGuildRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.DisbandGuildResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.LeaveGuildResponse> LeaveGuild(SharedNet.Api.LeaveGuildRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.LeaveGuildResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.JoinGuildResponse> JoinGuild(SharedNet.Api.JoinGuildRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.JoinGuildResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.ExpandGuildMembersResponse> ExpandGuildMembers(SharedNet.Api.ExpandGuildMembersRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.ExpandGuildMembersResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.GetGuildMembersResponse> GetGuildMembers(SharedNet.Api.GetGuildMembersRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.GetGuildMembersResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.PromoteGuildMemberResponse> PromoteGuildMember(SharedNet.Api.PromoteGuildMemberRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.PromoteGuildMemberResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.DemoteGuildMemberResponse> DemoteGuildMember(SharedNet.Api.DemoteGuildMemberRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.DemoteGuildMemberResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.KickGuildMemberResponse> KickGuildMember(SharedNet.Api.KickGuildMemberRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.KickGuildMemberResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.PlayerGuildJoinRequestResponse> RequestToJoinGuild(SharedNet.Api.PlayerGuildJoinRequestRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.PlayerGuildJoinRequestResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.GetPlayerGuildJoinRequestsResponse> GetPlayerGuildJoinRequests(SharedNet.Api.GetPlayerGuildJoinRequestsRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.GetPlayerGuildJoinRequestsResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.GetGuildJoinRequestsResponse> GetGuildJoinRequests(SharedNet.Api.GetGuildJoinRequestsRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.GetGuildJoinRequestsResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.AnswerGuildJoinRequestResponse> AnswerJoinRequest(SharedNet.Api.AnswerGuildJoinRequestRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.AnswerGuildJoinRequestResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.CancelJoinRequestResponse> CancelJoinRequest(SharedNet.Api.CancelJoinRequestRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.CancelJoinRequestResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.InviteGuildMemberResponse> InviteGuildMember(SharedNet.Api.InviteGuildMemberRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.InviteGuildMemberResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.GetPlayerGuildInvitesResponse> GetPlayerGuildInvites(SharedNet.Api.GetPlayerGuildInvitesRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.GetPlayerGuildInvitesResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.GetGuildInvitesResponse> GetGuildInvites(SharedNet.Api.GetGuildInvitesRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.GetGuildInvitesResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.AnswerGuildInviteResponse> AnswerGuildInvite(SharedNet.Api.AnswerGuildInviteRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.AnswerGuildInviteResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.CancelGuildInviteResponse> CancelGuildInvite(SharedNet.Api.CancelGuildInviteRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.CancelGuildInviteResponse>());
}

public sealed class GuildSiegeServiceApiImpl : ServiceBase<IGuildSiegeServiceApi>, IGuildSiegeServiceApi
{
    public MagicOnion.UnaryResult<SharedNet.Api.GetGuildSiegeCreateOrFindOptionsResponse> GetGuildSiegeCreateOrFindOptions(SharedNet.Api.GetGuildSiegeCreateOrFindOptionsRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.GetGuildSiegeCreateOrFindOptionsResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.CreateGuildSiegeResponse> CreateGuildSiege(SharedNet.Api.CreateGuildSiegeRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.CreateGuildSiegeResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.ListGuildSiegesResponse> ListGuildSieges(SharedNet.Api.ListGuildSiegesRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.ListGuildSiegesResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.FindGuildSiegeResponse> FindGuildSiege(SharedNet.Api.FindGuildSiegeRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.FindGuildSiegeResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.GetGuildSiegeDetailsResponse> GetGuildSiegeDetails(SharedNet.Api.GetGuildSiegeDetailsRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.GetGuildSiegeDetailsResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.JoinCreatedGuildSiegeResponse> JoinCreatedGuildSiege(SharedNet.Api.JoinCreatedGuildSiegeRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.JoinCreatedGuildSiegeResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.ChallengeGuildSiegeParticipantResponse> ChallengeGuildSiegeParticipant(SharedNet.Api.ChallengeGuildSiegeParticipantRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.ChallengeGuildSiegeParticipantResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.GetGuildSiegeModeInfoResponse> GetGuildSiegeModeInfo(SharedNet.Api.GetGuildSiegeModeInfoRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.GetGuildSiegeModeInfoResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.EndGuildSiegeBattleResponse> EndGuildSiegeBattle(SharedNet.Api.EndGuildSiegeBattleRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.EndGuildSiegeBattleResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.ClaimGuildSiegeRewardResponse> ClaimGuildSiegeReward(SharedNet.Api.ClaimGuildSiegeRewardRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.ClaimGuildSiegeRewardResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.SetCharacterGuildSiegeOptionsResponse> SetCharacterGuildSiegeOptions(SharedNet.Api.SetCharacterGuildSiegeOptionsRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.SetCharacterGuildSiegeOptionsResponse>());
}

public sealed class InventoryServiceApiImpl : ServiceBase<IInventoryServiceApi>, IInventoryServiceApi
{
    public MagicOnion.UnaryResult<SharedNet.Api.ItemOperationResponse> ItemOperation(SharedNet.Api.ItemOperationRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.ItemOperationResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.SortInventoryResponse> SortInventory(SharedNet.Api.SortInventoryRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.SortInventoryResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.GetInventoryResponse> GetInventory(SharedNet.Api.GetInventoryRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.GetInventoryResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.CraftRelicItemResponse> CraftRelicItem(SharedNet.Api.CraftRelicItemRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.CraftRelicItemResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.CraftEssenceItemResponse> CraftEssenceItem(SharedNet.Api.CraftEssenceItemRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.CraftEssenceItemResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.CraftEssenceItemResponse2> CraftEssenceItem2(SharedNet.Api.CraftEssenceItemRequest2 req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.CraftEssenceItemResponse2>());
    public MagicOnion.UnaryResult<SharedNet.Api.DisassembleItemsResponse> DisassembleItems(SharedNet.Api.DisassembleItemsRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.DisassembleItemsResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.MergePortalsResponse> MergePortals(SharedNet.Api.MergePortalsRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.MergePortalsResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.ConsumeItemResponse> ConsumeItem(SharedNet.Api.ConsumeItemRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.ConsumeItemResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.LockItemsResponse> LockItems(SharedNet.Api.LockItemsRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.LockItemsResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.SmeltItemsResponse> SmeltItems(SharedNet.Api.SmeltItemsRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.SmeltItemsResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.SocketItemResponse> SocketItem(SharedNet.Api.SocketItemRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.SocketItemResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.AddSocketItemResponse> ItemAddNewSocket(SharedNet.Api.AddSocketItemRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.AddSocketItemResponse>());
}

public sealed class LeaderboardServiceApiImpl : ServiceBase<ILeaderboardServiceApi>, ILeaderboardServiceApi
{
    public MagicOnion.UnaryResult<SharedNet.Api.GetRelevantLeaderboardsAndTournamentsResponse> GetRelevantLeaderboards(SharedNet.Api.GetRelevantLeaderboardsAndTournamentsRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.GetRelevantLeaderboardsAndTournamentsResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.ListLeaderboardRecordsResponse> ListLeaderboardRecords(SharedNet.Api.ListLeaderboardRecordsRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.ListLeaderboardRecordsResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.ListLeaderboardRecordsAroundOwnerResponse> ListLeaderboardRecordsAroundOwner(SharedNet.Api.ListLeaderboardRecordsAroundOwnerRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.ListLeaderboardRecordsAroundOwnerResponse>());
}

public sealed class MigrationServiceApiImpl : ServiceBase<IMigrationServiceApi>, IMigrationServiceApi
{
    public MagicOnion.UnaryResult<SharedNet.Api.RequestMigrationPackageResponse> RequestMigrationPackage(SharedNet.Api.RequestMigrationPackageRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.RequestMigrationPackageResponse>());
}

public sealed class ModeratorServiceApiImpl : ServiceBase<IModeratorServiceApi>, IModeratorServiceApi
{
    public MagicOnion.UnaryResult<SharedNet.Api.MuteUserResponse> MuteUser(SharedNet.Api.MuteUserRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.MuteUserResponse>());
}

public sealed class OfferingServiceApiImpl : ServiceBase<IOfferingServiceApi>, IOfferingServiceApi
{
    public MagicOnion.UnaryResult<SharedNet.Api.GetCurrentBlessingsResponse> GetCurrentBlessings(SharedNet.Api.GetCurrentBlessingsRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.GetCurrentBlessingsResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.MakeOfferingResponse> MakeOffering(SharedNet.Api.MakeOfferingRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.MakeOfferingResponse>());
}

public sealed class PartyServiceApiImpl : ServiceBase<IPartyServiceApi>, IPartyServiceApi
{
    public MagicOnion.UnaryResult<SharedNet.Api.GetTownPartyIdResponse> GetTownPartyId(SharedNet.Api.GetTownPartyIdRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.GetTownPartyIdResponse>());
}

public sealed class PlayfabServiceApiImpl : ServiceBase<IPlayfabServiceApi>, IPlayfabServiceApi
{
    public MagicOnion.UnaryResult<SharedNet.Api.MigrationResponse> MigrateAccountAsync(SharedNet.Api.MigrateAccountRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.MigrationResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.MigrationResponse> MigrateCharacterAsync(SharedNet.Api.MigrateCharacterRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.MigrationResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.FinalizeMigrationRespone> FinalizeMigrationAsync(SharedNet.Api.FinalizeMigrationRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.FinalizeMigrationRespone>());
    public MagicOnion.UnaryResult<SharedNet.Api.SkipMigrationResponse> SkipMigrationAsync(SharedNet.Api.SkipMigrationRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.SkipMigrationResponse>());
}

public sealed class SocialServiceApiImpl : ServiceBase<ISocialServiceApi>, ISocialServiceApi
{
    public MagicOnion.UnaryResult<SharedNet.Api.InspectCharacterResponse> InspectCharacter(SharedNet.Api.InspectCharacterRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.InspectCharacterResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.RedeemReferralResponse> RedeemReferral(SharedNet.Api.RedeemReferralRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.RedeemReferralResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.GetReferralsResponse> GetReferrals(SharedNet.Api.GetReferralsRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.GetReferralsResponse>());
}

public sealed class StoreServiceApiImpl : ServiceBase<IStoreServiceApi>, IStoreServiceApi
{
    public MagicOnion.UnaryResult<SharedNet.Api.GetStoreItemsResponse> GetStoreItems(SharedNet.Api.GetStoreItemsRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.GetStoreItemsResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.StartPurchaseResponse> StartPurchase(SharedNet.Api.StartPurchaseRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.StartPurchaseResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.PayForPurchaseResponse> PayForPurchase(SharedNet.Api.PayForPurchaseRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.PayForPurchaseResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.ConfirmPurchaseResponse> ConfirmPurchase(SharedNet.Api.ConfirmPurchaseRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.ConfirmPurchaseResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.ValidatedPurchaseResponse> ValidateGooglePlayPurchase(SharedNet.Api.ValidateGooglePlayPurchaseRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.ValidatedPurchaseResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.ValidatedPurchaseResponse> ValidateIOSPurchase(SharedNet.Api.ValidateIOSPurchaseRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.ValidatedPurchaseResponse>());
}

public sealed class TournamentServiceApiImpl : ServiceBase<ITournamentServiceApi>, ITournamentServiceApi
{
    public MagicOnion.UnaryResult<SharedNet.Api.ListTournamentRecordsResponse> ListTournamentRecords(SharedNet.Api.ListTournamentRecordsRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.ListTournamentRecordsResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.ListTournamentRecordsAroundOwnerResponse> ListTournamentRecordsAroundOwner(SharedNet.Api.ListTournamentRecordsAroundOwnerRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.ListTournamentRecordsAroundOwnerResponse>());
}

public sealed class UseItemServiceApiImpl : ServiceBase<IUseItemServiceApi>, IUseItemServiceApi
{
    public MagicOnion.UnaryResult<SharedNet.Api.UseItemAttributeRespecResponse> UseAttributeRespec(SharedNet.Api.UseItemAttributeRespecRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.UseItemAttributeRespecResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.UseItemWithBuffResponse> UseItemWithBuff(SharedNet.Api.UseItemWithBuffRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.UseItemWithBuffResponse>());
}

public sealed class UserLinkedAccountServiceApiImpl : ServiceBase<IUserLinkedAccountServiceApi>, IUserLinkedAccountServiceApi
{
    public MagicOnion.UnaryResult<SharedNet.Api.ChangeLinkedAccountPasswordResponse> ChangeLinkedAccountPassword(SharedNet.Api.ChangeLinkedAccountPasswordRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.ChangeLinkedAccountPasswordResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.LinkAccountResponse> LinkSteamAccount(SharedNet.Api.LinkSteamAccountRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.LinkAccountResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.LinkAccountResponse> LinkGoogleAccountAccount(SharedNet.Api.LinkGoogleAccountRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.LinkAccountResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.LinkAccountResponse> LinkGameCenterAccount(SharedNet.Api.LinkGameCenterAccountRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.LinkAccountResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.UnlinkAccountResponse> UnlinkSteamAccount(SharedNet.Api.UnlinkSteamAccountRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.UnlinkAccountResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.UnlinkAccountResponse> UnlinkGoogleAccount(SharedNet.Api.UnlinkGoogleAccountRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.UnlinkAccountResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.UnlinkAccountResponse> UnlinkGameCenterAccount(SharedNet.Api.UnlinkGameCenterAccountRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.UnlinkAccountResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.RegisterGameAccountResponse> RegisterGameAccount(SharedNet.Api.RegisterGameAccountRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.RegisterGameAccountResponse>());
}

public sealed class UserServiceApiImpl : ServiceBase<IUserServiceApi>, IUserServiceApi
{
    public MagicOnion.UnaryResult<SharedNet.Api.UnlockCharacterSlotResponse> UnlockCharacterSlot(SharedNet.Api.UnlockCharacterSlotRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.UnlockCharacterSlotResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.UpdateCheatInfoResponse> UpdateCheatInfo(SharedNet.Api.UpdateCheatInfoRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.UpdateCheatInfoResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.UnlockAchievementResponse> UnlockAchievement(SharedNet.Api.UnlockAchievementRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.UnlockAchievementResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.UnlockAvatarResponse> UnlockAvatar(SharedNet.Api.UnlockAvatarRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.UnlockAvatarResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.UnlockAvatarFrameResponse> UnlockAvatarFrame(SharedNet.Api.UnlockAvatarFrameRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.UnlockAvatarFrameResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.ChangeDisplayNameResponse> ChangeDisplayName(SharedNet.Api.ChangeDisplayNameRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.ChangeDisplayNameResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.SendDeviceInfoResponse> SendDeviceInfo(SharedNet.Api.SendDeviceInfoRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.SendDeviceInfoResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.GetSeasonMetadataResponse> GetSeasonMetadata(SharedNet.Api.GetSeasonMetadataRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.GetSeasonMetadataResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.ExportItemFilterResponse> ExportItemFilter(SharedNet.Api.ExportItemFilterRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.ExportItemFilterResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.FindItemFilterResponse> FindItemFilter(SharedNet.Api.FindItemFilterRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.FindItemFilterResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.DownloadItemFilterResponse> DownloadItemFilter(SharedNet.Api.DownloadItemFilterRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.DownloadItemFilterResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.ClaimSeasonalItemResponse> ClaimSeasonalItem(SharedNet.Api.ClaimSeasonalItemRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.ClaimSeasonalItemResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.UpgradeStashPageResponse> UpgradeStashPage(SharedNet.Api.UpgradeStashPageRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.UpgradeStashPageResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.DeleteAccountResponse> DeleteAccount(SharedNet.Api.DeleteAccountRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.DeleteAccountResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.GetUserTransactionsResponse> GetUserTransactions(SharedNet.Api.GetUserTransactionsRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.GetUserTransactionsResponse>());
}

public sealed class VirtualCurrencyServiceApiImpl : ServiceBase<IVirtualCurrencyServiceApi>, IVirtualCurrencyServiceApi
{
    public MagicOnion.UnaryResult<SharedNet.Api.GainVirtualCurrencyResponse> GainVirtualCurrency(SharedNet.Api.GainVirtualCurrencyRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.GainVirtualCurrencyResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.SpendVirtualCurrencyResponse> SpendVirtualCurrency(SharedNet.Api.SpendVirtualCurrencyRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.SpendVirtualCurrencyResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.GainSilverResponse> GainSilver(SharedNet.Api.GainSilverRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.GainSilverResponse>());
    public MagicOnion.UnaryResult<SharedNet.Api.SpendSilverResponse> SpendSilver(SharedNet.Api.SpendSilverRequest req) => UnaryResult.FromResult(Defaults.Create<SharedNet.Api.SpendSilverResponse>());
}

